// ─────────────────────────────────────────────────────────────────────────────
// QAmate first-run bootstrap
//
// QAmate is Electron + an embedded Python engine (Playwright, pydantic-ai, …).
// A packaged install ships the Electron app + source but NOT the Python
// environment (a venv is ~500 MB with Chromium and is not relocatable). So on
// first launch we provision a real virtualenv *next to the app* and install the
// Python deps + Chromium, showing a branded progress splash.
//
// Two roots:
//   APP_DIR  — the code (engine/, src/, tests/conftest.py, the demo suite). Read-only
//              inside a macOS .app under /Applications.
//   DATA_DIR — everything QAmate writes: venv/, config.json, results/, projects/,
//              the built-in tests/ suite, agent sessions and memory.
// In a dev checkout and on Windows they are the same folder (the NSIS installer is
// per-user, so its install dir is writable) — that layout is unchanged. A packaged
// macOS app uses ~/Library/Application Support/QAmate for DATA_DIR.
// QAMATE_DATA_DIR overrides the data root (testing the split layout from source).
//
// Base interpreter, in order of preference:
//   1. Bundled python-build-standalone at resources/pybundle/python (fully
//      offline; staged by scripts/prepare-bundle.ps1 before packaging).
//   2. A system Python 3.11+ (py -3.12 / py -3 / python / python3).
// If neither is available the app still opens; runs surface a clear message.
// ─────────────────────────────────────────────────────────────────────────────

const { app, BrowserWindow } = require('electron');
const path = require('path');
const fs = require('fs');
const { spawn, spawnSync } = require('child_process');

const APP_DIR = __dirname;
const IS_WIN = process.platform === 'win32';
const DATA_DIR = process.env.QAMATE_DATA_DIR ? path.resolve(process.env.QAMATE_DATA_DIR)
  : (app.isPackaged && process.platform === 'darwin') ? path.join(app.getPath('appData'), 'QAmate')
  : APP_DIR;

const VENV_DIR = path.join(DATA_DIR, 'venv');
const VENV_PYTHON = IS_WIN
  ? path.join(VENV_DIR, 'Scripts', 'python.exe')
  : path.join(VENV_DIR, 'bin', 'python');
const REQUIREMENTS = path.join(APP_DIR, 'requirements.txt');
const STAMP = path.join(VENV_DIR, '.qamate-env.json');

// Bump when requirements or provisioning steps change to force a re-provision.
const ENV_VERSION = '1';

// ── Interpreter discovery ────────────────────────────────────────────────────

/** Path to a bundled python-build-standalone interpreter, or null. */
function bundledPython() {
  const roots = app.isPackaged
    ? [path.join(process.resourcesPath, 'pybundle')]
    : [path.join(APP_DIR, 'build', 'pybundle')];
  const rel = IS_WIN ? ['python', 'python.exe'] : ['python', 'bin', 'python3'];
  for (const root of roots) {
    const p = path.join(root, ...rel);
    if (fs.existsSync(p)) return { cmd: p, args: [] };
  }
  return null;
}

/** A usable system Python 3.11+, or null. */
function systemPython() {
  const candidates = IS_WIN
    ? [['py', ['-3.12']], ['py', ['-3']], ['python', []], ['python3', []]]
    : [['python3', []], ['python', []]];
  for (const [cmd, pre] of candidates) {
    try {
      const r = spawnSync(cmd, [...pre, '-c', 'import sys;print("%d.%d" % sys.version_info[:2])'],
        { encoding: 'utf8', timeout: 15000, windowsHide: true });
      const out = ((r.stdout || '') + '').trim();
      const m = /^3\.(\d+)/.exec(out);
      if (r.status === 0 && m && parseInt(m[1], 10) >= 11) return { cmd, args: pre };
    } catch (_) { /* try next */ }
  }
  return null;
}

/** The base interpreter used to CREATE the venv (bundled preferred). */
function baseInterpreter() {
  return bundledPython() || systemPython();
}

// ── Readiness ────────────────────────────────────────────────────────────────

/**
 * True when the Python environment is provisioned and usable.
 * - A completed bootstrap writes a version stamp.
 * - A hand-made dev venv has no stamp: treat it as ready if Playwright is present
 *   so we never re-provision a working developer checkout.
 */
function pythonReady() {
  if (!fs.existsSync(VENV_PYTHON)) return false;
  try {
    const s = JSON.parse(fs.readFileSync(STAMP, 'utf8'));
    if (s && s.version === ENV_VERSION && s.complete === true) return true;
  } catch (_) { /* no/old stamp */ }
  const sp = IS_WIN
    ? path.join(VENV_DIR, 'Lib', 'site-packages', 'playwright')
    : path.join(VENV_DIR, 'lib');
  return fs.existsSync(sp);
}

// ── Data root (split layout only) ────────────────────────────────────────────

// Same loader as engine/project_store.py _CONFTEST_SHIM: the data-root suite
// reuses the app's shared conftest (fixtures, hooks, checkpoints, tracing).
const conftestShim = (appRoot) => `"""Auto-generated by QAmate on launch — do not edit.
Load shared ATS fixtures under a distinct module name, never this shim itself.
"""
import importlib.util
import os
import sys

_shared_path = os.path.join(os.environ.get("ATS_APP_ROOT") or ${JSON.stringify(appRoot)}, "tests", "conftest.py")
_spec = importlib.util.spec_from_file_location("_qamate_shared_conftest", _shared_path)
_shared = importlib.util.module_from_spec(_spec)
sys.modules[_spec.name] = _shared
_spec.loader.exec_module(_shared)
globals().update({name: getattr(_shared, name) for name in dir(_shared) if not name.startswith("__")})
`;

const noPycache = (src) => !src.split(path.sep).includes('__pycache__');

/** Copy from the (possibly read-only) app bundle and make the copy user-writable. */
function copyWritable(src, dest) {
  fs.cpSync(src, dest, { recursive: true, filter: noPycache });
  const walk = (p) => {
    const st = fs.statSync(p);
    fs.chmodSync(p, st.mode | 0o200);
    if (st.isDirectory()) for (const name of fs.readdirSync(p)) walk(path.join(p, name));
  };
  walk(dest);
}

/**
 * Make DATA_DIR usable. With the split layout, seed the built-in test suite from
 * the bundled demo flows on first run and refresh its conftest shim (which points
 * at this app's code, so moving QAmate.app keeps working). Never overwrites user flows.
 */
function ensureDataDir() {
  fs.mkdirSync(DATA_DIR, { recursive: true });
  if (DATA_DIR === APP_DIR) return;
  const appTests = path.join(APP_DIR, 'tests');
  const tests = path.join(DATA_DIR, 'tests');
  const flows = path.join(tests, 'flows');
  if (!fs.existsSync(flows)) {
    fs.mkdirSync(tests, { recursive: true });
    if (fs.existsSync(path.join(appTests, 'flows'))) copyWritable(path.join(appTests, 'flows'), flows);
    else fs.mkdirSync(flows, { recursive: true });
  }
  const fixtures = path.join(tests, 'fixtures');
  if (!fs.existsSync(fixtures) && fs.existsSync(path.join(appTests, 'fixtures'))) {
    copyWritable(path.join(appTests, 'fixtures'), fixtures);
  }
  for (const init of [path.join(tests, '__init__.py'), path.join(flows, '__init__.py')]) {
    if (!fs.existsSync(init)) fs.writeFileSync(init, '');
  }
  fs.writeFileSync(path.join(tests, 'conftest.py'), conftestShim(APP_DIR));
}

// ── Command runner (streams output to a callback) ────────────────────────────

function run(cmd, args, onLine) {
  return new Promise((resolve) => {
    let proc;
    try {
      proc = spawn(cmd, args, {
        cwd: DATA_DIR,
        env: { ...process.env, PYTHONUNBUFFERED: '1', PIP_DISABLE_PIP_VERSION_CHECK: '1' },
        windowsHide: true,
      });
    } catch (e) {
      onLine && onLine(`ERROR: ${e.message}`);
      return resolve(1);
    }
    const pump = (buf) => {
      for (const raw of buf.toString().split('\n')) {
        const line = raw.replace(/\r$/, '');
        if (line.trim() && onLine) onLine(line);
      }
    };
    proc.stdout.on('data', pump);
    proc.stderr.on('data', pump);
    proc.on('error', (e) => { onLine && onLine(`ERROR: ${e.message}`); resolve(1); });
    proc.on('close', (code) => resolve(code == null ? 1 : code));
  });
}

// ── Splash window ────────────────────────────────────────────────────────────

function createSplash(appIcon) {
  const win = new BrowserWindow({
    width: 560,
    height: 420,
    resizable: false,
    frame: false,
    show: true,
    backgroundColor: '#0B1220',
    title: 'Setting up QAmate',
    webPreferences: { contextIsolation: true, nodeIntegration: false },
    ...(appIcon ? { icon: appIcon } : {}),
  });
  win.loadFile(path.join(APP_DIR, 'src', 'setup.html'));
  return win;
}

async function splashCall(win, fn, ...args) {
  if (!win || win.isDestroyed()) return;
  const payload = JSON.stringify(args);
  try { await win.webContents.executeJavaScript(`window.${fn} && window.${fn}(...${payload});`); }
  catch (_) { /* window may be mid-load */ }
}

// ── Orchestration ────────────────────────────────────────────────────────────

const STEPS = [
  { key: 'venv', label: 'Creating Python environment' },
  { key: 'pip', label: 'Upgrading installer tools' },
  { key: 'deps', label: 'Installing Python dependencies' },
  { key: 'browser', label: 'Installing the Chromium browser' },
];

/**
 * Provision the Python environment with a progress splash.
 * Resolves { ok:true } or { ok:false, message } — the caller opens the main
 * window regardless so the app is usable (runs will report the missing env).
 */
async function runFirstRunSetup(appIcon) {
  const win = createSplash(appIcon);
  // Give the splash a moment to load before we start pushing updates.
  await new Promise((r) => win.webContents.once('did-finish-load', r));

  const log = (line) => splashCall(win, 'qamateLog', line);
  const setStep = (i, detail) => splashCall(win, 'qamateStep', i, STEPS.length, STEPS[i].label, detail || '');

  const base = baseInterpreter();
  if (!base) {
    await splashCall(win, 'qamateFail', IS_WIN
      ? 'Python 3.11+ was not found. Install Python 3.12 from python.org (tick "Add to PATH"), then relaunch QAmate.'
      : 'Python 3.11+ was not found. Install it (for example: brew install python@3.12), then relaunch QAmate.');
    await new Promise((r) => setTimeout(r, 60000));
    if (!win.isDestroyed()) win.close();
    return { ok: false, message: 'No Python interpreter available' };
  }

  await log(`Using base interpreter: ${base.cmd} ${base.args.join(' ')}`.trim());

  try {
    fs.mkdirSync(DATA_DIR, { recursive: true });

    // 1) venv
    await setStep(0);
    if (!fs.existsSync(VENV_PYTHON)) {
      const code = await run(base.cmd, [...base.args, '-m', 'venv', VENV_DIR], log);
      if (code !== 0 || !fs.existsSync(VENV_PYTHON)) throw new Error('Failed to create the virtual environment.');
    } else {
      await log('Existing environment found — reusing.');
    }

    // 2) pip / wheel
    await setStep(1);
    await run(VENV_PYTHON, ['-m', 'pip', 'install', '--upgrade', 'pip', 'wheel'], log);

    // 3) requirements
    await setStep(2);
    const depsCode = await run(VENV_PYTHON, ['-m', 'pip', 'install', '-r', REQUIREMENTS], log);
    if (depsCode !== 0) throw new Error('pip failed to install the Python dependencies.');

    // 4) Chromium
    await setStep(3);
    const browserCode = await run(VENV_PYTHON, ['-m', 'playwright', 'install', 'chromium'], log);
    if (browserCode !== 0) await log('WARNING: Chromium download reported an error — you can retry later from Settings.');

    fs.writeFileSync(STAMP, JSON.stringify({
      version: ENV_VERSION,
      complete: true,
      base: base.cmd,
      created_at: new Date().toISOString(),
    }, null, 2));

    await splashCall(win, 'qamateDone');
    await new Promise((r) => setTimeout(r, 900));
    if (!win.isDestroyed()) win.close();
    return { ok: true };
  } catch (e) {
    await splashCall(win, 'qamateFail', `Setup could not finish: ${e.message}`);
    await new Promise((r) => setTimeout(r, 60000));
    if (!win.isDestroyed()) win.close();
    return { ok: false, message: e.message };
  }
}

module.exports = {
  APP_DIR,
  DATA_DIR,
  ensureDataDir,
  VENV_DIR,
  VENV_PYTHON,
  ENV_VERSION,
  pythonReady,
  baseInterpreter,
  bundledPython,
  systemPython,
  runFirstRunSetup,
};
