"""
Agrim ATS — Project Store
=========================

A **Project** is the unit a customer points the tool at: one web app, its
environments, how to log in, which LLM provider to use, and its PRD. This is the
generalization that turns the (formerly Agrim-hardcoded) engine into a tool any
team can run against their own app.

Layout (all under <ats_root>/projects/):
    projects/
      _index.json                 -> {"active": "<project-id>"}
      <project-id>/
        project.json              -> the project (schema below)
        auth/storage_state.json   -> captured login (Playwright storage_state)
        app_model.json            -> App Explorer output (Phase 1)
        requirements.json         -> PRD Extractor output (Phase 2)
        context/                  -> user-supplied context files the AI agent can read
        AGENT_MEMORY.md           -> the agent's durable, self-updated memory (CLAUDE.md-style)

project.json schema (schema_version 1):
{
  "schema_version": 1,
  "id": "acme-app",
  "name": "Acme App",
  "created_at": "2026-05-29T...",
  "environments": { "dev": "https://dev.acme.test/", "prod": "https://acme.test/" },
  "default_environment": "dev",
  "auth": {
    "type": "none" | "storage_state" | "login_steps",
    "storage_state": "auth/storage_state.json",   # relative to the project dir
    "login_path": "login",                          # optional, for heuristic login
    "credentials": { "email": "", "password": "" }  # optional, only if type==login_steps
  },
  "llm_ref": "default",        # which entry in config.json "llm.providers" to use
  "prd_path": null,            # absolute or project-relative path to a PRD .md
  "context_dir": null,         # optional ABSOLUTE path to an existing docs folder the
                               # agent may read; null = managed projects/<id>/context/
  "rules": {                   # opt-in, per-project behaviour (Phase 4)
    "mui_quirks": false,
    "broken_selector_fixes": false
  }
}

Node (main.js) owns CRUD from the UI; this module is the Python read-side used by
conftest / runner / app_explorer. Both agree on the schema above. Pure stdlib.
"""

import os
import re
import json
import datetime

SCHEMA_VERSION = 1


# ── Paths ────────────────────────────────────────────────────────────────────

def projects_dir(ats_root):
    return os.path.join(ats_root, "projects")


def _index_path(ats_root):
    return os.path.join(projects_dir(ats_root), "_index.json")


def project_dir(ats_root, project_id):
    return os.path.join(projects_dir(ats_root), project_id)


def project_file(ats_root, project_id):
    return os.path.join(project_dir(ats_root, project_id), "project.json")


def storage_state_path(ats_root, project_id):
    """Absolute path to a project's captured login state (may not exist yet)."""
    return os.path.join(project_dir(ats_root, project_id), "auth", "storage_state.json")


# ── Per-project test suite ────────────────────────────────────────────────────
# Each project owns its OWN tests (projects/<id>/tests/flows/...), so a new
# project starts empty — the legacy Agrim suite (<ats_root>/tests) is used only
# when no project is targeted. The same flows/<flow>/{test_*.py, test_cases.json,
# test_data.json} layout applies in both, so every existing tool works unchanged.

def tests_root(ats_root, project_id=None):
    """The tests directory for a project (projects/<id>/tests), or the legacy
    shared suite (<ats_root>/tests) when project_id is falsy."""
    if project_id:
        return os.path.join(project_dir(ats_root, project_id), "tests")
    return os.path.join(ats_root, "tests")


def resolve_tests_root(ats_root, project_id=None):
    """The tests root that is ACTUALLY in effect: a project's own suite only when
    it exists (created via create_project / explicit activation). Projects created
    before per-project suites (e.g. the original 'test' agent project) keep using
    the legacy shared suite — nothing silently moves."""
    if project_id:
        own = tests_root(ats_root, project_id)
        if os.path.isdir(own):
            return own
    return os.path.join(ats_root, "tests")


_CONFTEST_SHIM = '''"""Auto-generated by project_store — do not edit.
Reuses the shared ATS conftest (fixtures, hooks, checkpoint runner, tracing,
network capture) for this project's tests. pytest only discovers conftest files
above the test path, so each project tests dir carries this shim.
"""
import os, sys

_ATS_TESTS = os.path.join(
    os.environ.get("ATS_ROOT", {ats_root!r}), "tests")
if _ATS_TESTS not in sys.path:
    sys.path.insert(0, _ATS_TESTS)

from conftest import *  # noqa: F401,F403 — fixtures + pytest hooks resolve by name
'''


def ensure_tests_scaffold(ats_root, project_id):
    """Create projects/<id>/tests/{conftest.py, flows/__init__.py} if missing.
    Idempotent; returns the tests root."""
    root = tests_root(ats_root, project_id)
    if not project_id:
        return root
    flows = os.path.join(root, "flows")
    os.makedirs(flows, exist_ok=True)
    shim = os.path.join(root, "conftest.py")
    if not os.path.exists(shim):
        with open(shim, "w", encoding="utf-8") as f:
            f.write(_CONFTEST_SHIM.format(ats_root=ats_root))
    init = os.path.join(flows, "__init__.py")
    if not os.path.exists(init):
        open(init, "w", encoding="utf-8").close()
    return root


def app_model_path(ats_root, project_id):
    return os.path.join(project_dir(ats_root, project_id), "app_model.json")


def ui_map_path(ats_root, project_id):
    return os.path.join(project_dir(ats_root, project_id), "ui_map.json")


def requirements_path(ats_root, project_id):
    return os.path.join(project_dir(ats_root, project_id), "requirements.json")


# ── AI-agent context folder + memory file ─────────────────────────────────────
# These give the chat agent (engine/agent_chat.py) durable knowledge of the app:
#   context/         user-supplied docs/screenshots the agent reads on demand
#   AGENT_MEMORY.md  a CLAUDE.md-style memory the agent reads + updates itself
# main.js replicates the SAME path convention (projects/<id>/context,
# projects/<id>/AGENT_MEMORY.md; <ats_root>/.agent_context/ when there is no
# project) — keep the two in sync.

def context_dir(ats_root, project_id):
    """Managed folder of context files. projects/<id>/context/ — or, when there is
    no project (legacy Agrim), <ats_root>/.agent_context/."""
    if project_id:
        return os.path.join(project_dir(ats_root, project_id), "context")
    return os.path.join(ats_root, ".agent_context")


def memory_path(ats_root, project_id):
    """The agent's durable memory file. projects/<id>/AGENT_MEMORY.md — or, with no
    project, <ats_root>/.agent_context/AGENT_MEMORY.md."""
    if project_id:
        return os.path.join(project_dir(ats_root, project_id), "AGENT_MEMORY.md")
    return os.path.join(ats_root, ".agent_context", "AGENT_MEMORY.md")


def resolve_context_dir(ats_root, project_id, project=None, create=True):
    """The context folder the agent actually reads: an ABSOLUTE project.json
    'context_dir' override if set, else the managed location. Created on demand."""
    proj = project if isinstance(project, dict) else get_project(ats_root, project_id)
    override = (proj or {}).get("context_dir")
    path = override if (override and os.path.isabs(override)) else context_dir(ats_root, project_id)
    if create:
        try:
            os.makedirs(path, exist_ok=True)
        except Exception:
            pass
    return path


def resolve_memory_path(ats_root, project_id, create=True):
    """The agent's memory file path (its parent dir is created when create=True)."""
    path = memory_path(ats_root, project_id)
    if create:
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
        except Exception:
            pass
    return path


# ── Helpers ──────────────────────────────────────────────────────────────────

def _read_json(path, default=None):
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return default


def _write_json(path, data):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)


def slugify(name):
    s = re.sub(r"[^a-z0-9]+", "-", (name or "").strip().lower()).strip("-")
    return s or "project"


def _unique_id(ats_root, base):
    """Return a project id based on `base`, suffixed if it already exists."""
    existing = {p["id"] for p in list_projects(ats_root)}
    if base not in existing:
        return base
    i = 2
    while f"{base}-{i}" in existing:
        i += 1
    return f"{base}-{i}"


def _normalize_url(url):
    url = (url or "").strip()
    if url and not url.endswith("/"):
        url += "/"
    return url


# ── CRUD ─────────────────────────────────────────────────────────────────────

def list_projects(ats_root):
    """All projects (sorted by name). Missing/empty projects dir → []."""
    d = projects_dir(ats_root)
    if not os.path.isdir(d):
        return []
    out = []
    for entry in sorted(os.listdir(d)):
        pf = project_file(ats_root, entry)
        if os.path.exists(pf):
            proj = _read_json(pf)
            if isinstance(proj, dict) and proj.get("id"):
                out.append(proj)
    out.sort(key=lambda p: (p.get("name") or p.get("id") or "").lower())
    return out


def get_project(ats_root, project_id):
    if not project_id:
        return None
    return _read_json(project_file(ats_root, project_id))


def create_project(ats_root, name, base_url, environment="dev", **extra):
    """Create a new project and make it active. Returns the project dict.
    extra['apps'] = [{label, url, email?, password?}] for multi-surface projects
    (e.g. storefront + admin panel); the first app is the primary base URL."""
    pid = _unique_id(ats_root, slugify(name))
    apps = _sanitize_apps(extra.get("apps"))
    base = _normalize_url(base_url) or (apps[0]["url"] if apps else "")
    proj = {
        "schema_version": SCHEMA_VERSION,
        "id": pid,
        "name": name or pid,
        "created_at": datetime.datetime.now().isoformat(timespec="seconds"),
        "apps": apps,
        "environments": {environment: base},
        "default_environment": environment,
        "auth": {
            "type": extra.get("auth_type", "none"),
            "storage_state": "auth/storage_state.json",
            "login_path": extra.get("login_path", "login"),
            "credentials": extra.get("credentials", {"email": "", "password": ""}),
        },
        "llm_ref": extra.get("llm_ref", "default"),
        "prd_path": extra.get("prd_path"),
        "context_dir": extra.get("context_dir"),
        "rules": {"mui_quirks": False, "broken_selector_fixes": False},
    }
    _write_json(project_file(ats_root, pid), proj)
    ensure_tests_scaffold(ats_root, pid)   # fresh, empty test suite of its own
    set_active_project_id(ats_root, pid)
    return proj


def update_project(ats_root, project_id, patch):
    """Shallow-merge `patch` into a project (one level deep for dict values)."""
    proj = get_project(ats_root, project_id)
    if proj is None:
        return None
    for k, v in (patch or {}).items():
        if isinstance(v, dict) and isinstance(proj.get(k), dict):
            proj[k] = {**proj[k], **v}
        else:
            proj[k] = v
    _write_json(project_file(ats_root, project_id), proj)
    return proj


def delete_project(ats_root, project_id):
    import shutil
    d = project_dir(ats_root, project_id)
    if os.path.isdir(d):
        shutil.rmtree(d, ignore_errors=True)
    if get_active_project_id(ats_root) == project_id:
        remaining = list_projects(ats_root)
        set_active_project_id(ats_root, remaining[0]["id"] if remaining else None)
    return True


# ── Active project ───────────────────────────────────────────────────────────

def get_active_project_id(ats_root):
    idx = _read_json(_index_path(ats_root), {}) or {}
    active = idx.get("active")
    if active and os.path.exists(project_file(ats_root, active)):
        return active
    # An EXPLICIT null means "built-in suite" (user's choice) — honor it.
    if "active" in idx and not active:
        return None
    # Key missing / stale id: fall back to the first project.
    projs = list_projects(ats_root)
    return projs[0]["id"] if projs else None


def set_active_project_id(ats_root, project_id):
    _write_json(_index_path(ats_root), {"active": project_id})


def get_active_project(ats_root):
    return get_project(ats_root, get_active_project_id(ats_root))


# ── Resolution helpers (used by conftest / runner / explorer) ─────────────────

def _sanitize_apps(apps):
    """Normalize an apps list: [{label, url, credentials{email,password}}].
    Entries without a URL are dropped; URLs are normalized."""
    out = []
    for a in apps or []:
        if not isinstance(a, dict):
            continue
        url = _normalize_url(a.get("url"))
        if not url:
            continue
        cred = a.get("credentials") or {}
        out.append({
            "label": (a.get("label") or "").strip() or f"App {len(out) + 1}",
            "url": url,
            "credentials": {"email": (cred.get("email") or a.get("email") or "").strip(),
                            "password": cred.get("password") or a.get("password") or ""},
        })
    return out


def project_apps(project):
    """The list of apps (base URLs) a project targets. A project may have several
    surfaces (e.g. a storefront AND an admin panel). Projects created before the
    apps field get a single synthesized entry from their environment URL."""
    if not project:
        return []
    apps = _sanitize_apps(project.get("apps"))
    if apps:
        return apps
    url = resolve_base_url(project)
    if not url:
        return []
    cred = ((project.get("auth") or {}).get("credentials")) or {}
    return [{"label": project.get("name") or "App", "url": url,
             "credentials": {"email": cred.get("email", ""), "password": cred.get("password", "")}}]


def resolve_base_url(project, environment=None):
    """The PRIMARY base URL for a project: the first app when apps are defined,
    else the environment URL (falls back to default env)."""
    if not project:
        return ""
    apps = _sanitize_apps(project.get("apps"))
    if apps:
        return apps[0]["url"]
    envs = project.get("environments", {}) or {}
    env = environment or project.get("default_environment")
    url = envs.get(env) or (next(iter(envs.values()), "") if envs else "")
    return _normalize_url(url)


def has_storage_state(ats_root, project_id):
    return os.path.exists(storage_state_path(ats_root, project_id))


# ── CLI (so Node/scripts can drive it without duplicating logic) ──────────────

def _emit(obj):
    print(json.dumps(obj, default=str))


def main(argv):
    if len(argv) < 2:
        _emit({"status": "error", "message": "usage: project_store.py <list|get|create|update|set-active|delete> [args]"})
        return 1
    ats_root = os.environ.get("ATS_ROOT") or os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    cmd = argv[1]

    if cmd == "list":
        projs = list_projects(ats_root)
        for p in projs:   # UI hint: does this project own a test suite yet?
            p["_has_suite"] = os.path.isdir(tests_root(ats_root, p["id"]))
        _emit({"status": "success", "active": get_active_project_id(ats_root), "projects": projs})
    elif cmd == "get":
        _emit({"status": "success", "project": get_project(ats_root, argv[2] if len(argv) > 2 else get_active_project_id(ats_root))})
    elif cmd == "create":
        # project_store.py create <name> <base_url> [environment]
        if len(argv) < 4:
            _emit({"status": "error", "message": "usage: create <name> <base_url> [environment]"})
            return 1
        env = argv[4] if len(argv) > 4 else "dev"
        _emit({"status": "success", "project": create_project(ats_root, argv[2], argv[3], env)})
    elif cmd == "create-json":
        # project_store.py create-json '{"name":..,"baseUrl":..,"environment":..,"apps":[{label,url,email,password}]}'
        if len(argv) < 3:
            _emit({"status": "error", "message": "usage: create-json <json>"})
            return 1
        spec = json.loads(argv[2])
        _emit({"status": "success", "project": create_project(
            ats_root, spec.get("name"), spec.get("baseUrl") or "",
            spec.get("environment") or "dev", apps=spec.get("apps") or [])})
    elif cmd == "update":
        # project_store.py update <id> <json-patch>
        if len(argv) < 4:
            _emit({"status": "error", "message": "usage: update <id> <json-patch>"})
            return 1
        _emit({"status": "success", "project": update_project(ats_root, argv[2], json.loads(argv[3]))})
    elif cmd == "set-active":
        # '' or '-' selects the built-in legacy suite (active = null).
        pid = argv[2] if len(argv) > 2 and argv[2] not in ("", "-") else None
        set_active_project_id(ats_root, pid)
        _emit({"status": "success", "active": pid})
    elif cmd == "delete":
        delete_project(ats_root, argv[2])
        _emit({"status": "success"})
    else:
        _emit({"status": "error", "message": f"unknown command: {cmd}"})
        return 1
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main(sys.argv))
