"""
QAmate — Self-Healing Locators
==================================

The foundation that lets generated tests survive UI changes instead of breaking
on the first renamed class, regenerated id, or reordered element. This is what
turns "record / play / fix, repeat" into "runs without issues", and it's the
keystone the autonomous pipeline (explore → generate → run) is built on:
auto-generated tests are only worth anything if they don't rot.

How healing works — three tiers, cheapest first:

  1. PRIMARY      The locator the test was authored/recorded with.
  2. FALLBACKS    Alternative strategies derived from the SAME element identity
                  (role+name, visible text, test-id, label, a relaxed CSS). If
                  the primary drifts but the element is still "the Save button",
                  one of these still finds it.
  3. FINGERPRINT  Last resort: scan the page for the element whose identity
                  (tag, role, accessible name, text, key attributes) is most
                  similar to the one captured when the test last passed, and
                  accept it above a confidence threshold.

Every heal is recorded (primary → which strategy won, with a confidence score)
so the run report can show "4 locators auto-healed" and later offer to commit
the repaired locator back into the test — i.e. self-maintenance, a real
sellable capability, not just resilience.

The engine is framework-thin: it speaks Playwright's `Page`/`Locator` but keeps
locator *strategies* as plain dicts so they can be stored in test_data/JSON,
generated by the synthesizer, or emitted by the recorder.

Strategy dict forms (the `by` key selects the resolver):
    {"by": "role", "role": "button", "name": "Save", "exact": false}
    {"by": "test_id", "value": "save-btn"}
    {"by": "text", "value": "Save", "exact": false}
    {"by": "label", "value": "Email"}
    {"by": "placeholder", "value": "Search products"}
    {"by": "alt", "value": "logo"}
    {"by": "title", "value": "Close"}
    {"by": "css", "value": "#save-btn"}
    {"by": "xpath", "value": "//button[@type='submit']"}
"""

import os
import re
import json
import difflib


class SelfHealError(Exception):
    """Raised when no strategy (primary, fallback, or fingerprint) resolves."""


# role → most-likely HTML tag, used to narrow the fingerprint scan.
_ROLE_TAG = {
    "button": "button",
    "link": "a",
    "textbox": "input",
    "checkbox": "input",
    "radio": "input",
    "combobox": "select",
    "heading": "h1,h2,h3,h4,h5,h6",
    "img": "img",
    "listitem": "li",
    "menuitem": "[role=menuitem]",
    "tab": "[role=tab]",
}


# ── Strategy dict → Playwright Locator ──────────────────────────────────────

def to_locator(page, strat):
    """Build a Playwright Locator from a strategy dict. Returns None if the
    strategy is malformed (so callers can simply skip it)."""
    try:
        by = strat.get("by")
        if by == "role":
            kwargs = {}
            if strat.get("name"):
                kwargs["name"] = strat["name"]
            if "exact" in strat:
                kwargs["exact"] = bool(strat["exact"])
            return page.get_by_role(strat["role"], **kwargs)
        if by == "test_id":
            return page.get_by_test_id(strat["value"])
        if by == "text":
            return page.get_by_text(strat["value"], exact=bool(strat.get("exact", False)))
        if by == "label":
            return page.get_by_label(strat["value"], exact=bool(strat.get("exact", False)))
        if by == "placeholder":
            return page.get_by_placeholder(strat["value"])
        if by == "alt":
            return page.get_by_alt_text(strat["value"])
        if by == "title":
            return page.get_by_title(strat["value"])
        if by == "css":
            return page.locator(strat["value"])
        if by == "xpath":
            return page.locator("xpath=" + strat["value"])
    except Exception:
        return None
    return None


def _describe(strat):
    """Compact human/log description of a strategy dict."""
    by = strat.get("by", "?")
    if by == "role":
        return f'role={strat.get("role")} name={strat.get("name")!r}'
    return f'{by}={strat.get("value")!r}'


# ── Recorded locator string → strategies + fingerprint ──────────────────────

def derive_strategies(primary):
    """Decompose a recorded Playwright locator (string OR strategy dict) into
    (primary_dict, fallbacks, fingerprint).

    A recorder/synthesizer captures one locator; healing needs *alternatives*
    that point at the same element. We derive them from the element identity
    encoded in the primary so the test self-heals even with no extra metadata.
    """
    if isinstance(primary, dict):
        return primary, _auto_fallbacks(primary), _fingerprint_for(primary)

    s = str(primary).strip()

    m = re.search(r'get_by_role\(\s*["\'](\w+)["\']\s*(?:,\s*name\s*=\s*["\'](.*?)["\'])?', s)
    if m:
        prim = {"by": "role", "role": m.group(1)}
        if m.group(2):
            prim["name"] = m.group(2)
        return prim, _auto_fallbacks(prim), _fingerprint_for(prim)

    m = re.search(r'get_by_test_id\(\s*["\'](.*?)["\']', s)
    if m:
        prim = {"by": "test_id", "value": m.group(1)}
        return prim, _auto_fallbacks(prim), _fingerprint_for(prim)

    m = re.search(r'get_by_text\(\s*["\'](.*?)["\']', s)
    if m:
        prim = {"by": "text", "value": m.group(1)}
        return prim, _auto_fallbacks(prim), _fingerprint_for(prim)

    m = re.search(r'get_by_label\(\s*["\'](.*?)["\']', s)
    if m:
        prim = {"by": "label", "value": m.group(1)}
        return prim, _auto_fallbacks(prim), _fingerprint_for(prim)

    m = re.search(r'get_by_placeholder\(\s*["\'](.*?)["\']', s)
    if m:
        prim = {"by": "placeholder", "value": m.group(1)}
        return prim, _auto_fallbacks(prim), _fingerprint_for(prim)

    m = re.search(r'(?:page\.)?locator\(\s*r?["\'](.*?)["\']\s*\)', s)
    if m:
        prim = {"by": "css", "value": m.group(1)}
        return prim, _auto_fallbacks(prim), _fingerprint_for(prim)

    # Unknown form — treat the whole thing as a CSS selector.
    prim = {"by": "css", "value": s}
    return prim, [], {}


def _auto_fallbacks(prim):
    """Derive same-element alternative strategies from a primary strategy."""
    by = prim.get("by")
    fbs = []
    if by == "role":
        name = prim.get("name")
        role = prim.get("role")
        if name:
            fbs.append({"by": "text", "value": name})
            tag = _ROLE_TAG.get(role, "")
            first_tag = tag.split(",")[0] if tag else ""
            if first_tag and not first_tag.startswith("["):
                # relaxed CSS: tag containing the visible name
                fbs.append({"by": "css", "value": f'{first_tag}:has-text("{name}")'})
    elif by == "test_id":
        fbs.append({"by": "css", "value": f'[data-testid="{prim["value"]}"]'})
    elif by == "text":
        fbs.append({"by": "role", "role": "button", "name": prim["value"]})
        fbs.append({"by": "role", "role": "link", "name": prim["value"]})
    elif by == "label":
        fbs.append({"by": "placeholder", "value": prim["value"]})
    return fbs


def _fingerprint_for(prim):
    """Best-effort identity fingerprint from a primary strategy."""
    by = prim.get("by")
    fp = {}
    if by == "role":
        fp["role"] = prim.get("role")
        tag = _ROLE_TAG.get(prim.get("role"), "")
        if tag and "," not in tag and not tag.startswith("["):
            fp["tag"] = tag
        if prim.get("name"):
            fp["name"] = prim["name"]
            fp["text"] = prim["name"]
    elif by in ("text", "label"):
        fp["text"] = prim.get("value")
        fp["name"] = prim.get("value")
    elif by == "test_id":
        fp["test_id"] = prim.get("value")
    return fp


# ── Heal recording ──────────────────────────────────────────────────────────

class Healer:
    """Collects heal events for one test so the report can show what drifted."""

    def __init__(self, tc_id):
        self.tc_id = tc_id
        self.events = []

    def record(self, label, primary, healed_via, score=None):
        evt = {
            "label": label,
            "primary": _describe(primary),
            "healed_via": _describe(healed_via),
            "tier": "fingerprint" if healed_via.get("by") == "fingerprint" else "fallback",
        }
        if score is not None:
            evt["confidence"] = round(score, 3)
        self.events.append(evt)
        # ASCII only: this stdout is piped through the Electron runner and the
        # Windows console is cp1252 — a unicode arrow would crash mid-test.
        print(f"[HEAL] {self.tc_id}: '{label or _describe(primary)}' drifted -> "
              f"recovered via {evt['healed_via']} ({evt['tier']}"
              f"{'' if score is None else f', conf={evt['confidence']}'})", flush=True)

    def write(self, path):
        if not self.events:
            return
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            json.dump({"tc_id": self.tc_id, "heals": self.events}, f, indent=2)


# ── The self-healing locator ─────────────────────────────────────────────────

class SmartLocator:
    """Resolves an element through primary → fallbacks → fingerprint scan,
    recording any heal. `resolve()` returns a normal Playwright Locator, so the
    rest of the test reads exactly like hand-written Playwright."""

    def __init__(self, page, primary, *, fallbacks=None, fingerprint=None,
                 healer=None, label=None, fingerprint_threshold=0.6):
        prim, derived_fbs, derived_fp = derive_strategies(primary)
        self.page = page
        self.primary = prim
        # Explicit fallbacks/fingerprint (e.g. captured at record time) take
        # precedence but are merged with the auto-derived ones.
        self.fallbacks = list(fallbacks) if fallbacks else []
        for fb in derived_fbs:
            if fb not in self.fallbacks:
                self.fallbacks.append(fb)
        self.fingerprint = {**derived_fp, **(fingerprint or {})}
        self.healer = healer
        self.label = label or _describe(prim)
        self.threshold = fingerprint_threshold

    def _try(self, strat, timeout):
        loc = to_locator(self.page, strat)
        if loc is None:
            return None
        try:
            loc.first.wait_for(state="attached", timeout=timeout)
            return loc.first
        except Exception:
            return None

    def _fingerprint_scan(self):
        fp = self.fingerprint
        target = (fp.get("name") or fp.get("text") or "").strip().lower()
        if not target:
            return None, 0.0
        scope = fp.get("tag") or (_ROLE_TAG.get(fp.get("role"), "") or "button,a,input,[role]")
        try:
            cands = self.page.locator(scope)
            n = min(cands.count(), 200)
        except Exception:
            return None, 0.0
        best, best_score = None, 0.0
        for i in range(n):
            el = cands.nth(i)
            try:
                aria = (el.get_attribute("aria-label") or "").strip().lower()
                txt = (el.text_content() or "").strip().lower()
            except Exception:
                continue
            cand = aria or txt
            if not cand:
                continue
            score = difflib.SequenceMatcher(None, target, cand).ratio()
            # exact substring is a strong signal
            if target and (target in cand or cand in target):
                score = max(score, 0.85)
            if score > best_score:
                best_score, best = score, el
        if best is not None and best_score >= self.threshold:
            return best, best_score
        return None, best_score

    def resolve(self, timeout_ms=5000, fallback_timeout_ms=1200):
        """Return a resolved Playwright Locator, healing if the primary drifted.
        Raises SelfHealError if nothing matches (fail loud, never silently)."""
        m = self._try(self.primary, timeout_ms)
        if m is not None:
            return m

        for fb in self.fallbacks:
            m = self._try(fb, fallback_timeout_ms)
            if m is not None:
                if self.healer:
                    self.healer.record(self.label, self.primary, fb)
                return m

        m, score = self._fingerprint_scan()
        if m is not None:
            if self.healer:
                self.healer.record(self.label, self.primary, {"by": "fingerprint"}, score=score)
            return m

        raise SelfHealError(
            f"Could not resolve '{self.label}': tried primary ({_describe(self.primary)}), "
            f"{len(self.fallbacks)} fallback(s), and a fingerprint scan."
        )


def smart_locator(page, primary, **kwargs):
    """Convenience constructor: smart_locator(page, 'get_by_role(...)').resolve().click()"""
    return SmartLocator(page, primary, **kwargs)
