"""Orders flow — Purchase Order E2E tests.

Tests are auto-generated by the ATS recorder.
Record a flow in the app, review steps, add assertions, and save.
"""

import re
import pytest
from playwright.sync_api import expect, Page

@pytest.mark.tc("TC-ORDERS-001")
def test_TC_ORDERS_001(page: Page, tc_data, base_url, admin_url, checkpoints):
    """Create Inv PO
    """
    # Step 1: Navigate to Navigate to https://admin-dev.agrim.app/#/login
    page.goto(admin_url + "#/login")
    # Step 2: Enter "amit.dalal@agrim.app" in Textbox "Username"
    page.get_by_role("textbox", name="Username").fill(tc_data.get("input_1", ""))
    page.wait_for_timeout(1000)
    # Step 3: Click Textbox "Password"
    page.get_by_role("textbox", name="Password").click()
    page.wait_for_timeout(1000)
    # Step 4: Press "CapsLock" on Press "CapsLock" on Textbox "Password"
    page.get_by_role("textbox", name="Password").press("CapsLock")
    page.wait_for_timeout(1000)
    # Step 5: Enter "A" in Textbox "Password"
    page.get_by_role("textbox", name="Password").fill(tc_data.get("input_2", ""))
    page.wait_for_timeout(1000)
    # Step 6: Press "CapsLock" on Press "CapsLock" on Textbox "Password"
    page.get_by_role("textbox", name="Password").press("CapsLock")
    page.wait_for_timeout(1000)
    # Step 7: Enter "Amit@12345" in Textbox "Password"
    page.get_by_role("textbox", name="Password").fill(tc_data.get("input_3", ""))
    page.wait_for_timeout(1000)
    # Step 8: Click Button "Sign in"
    page.get_by_role("button", name="Sign in").click()
    page.wait_for_timeout(1000)
    # Step 9: Click Button "user icon Purchase orders"
    page.get_by_role("button", name="user icon Purchase orders").click()
    page.wait_for_timeout(1000)
    # Step 10: Click Menuitem "All Orders"
    page.get_by_role("menuitem", name="All Orders").click()
    page.wait_for_timeout(1000)
    # Step 11: Click Text "Create"
    page.get_by_text("Create", exact=True).click()
    page.wait_for_timeout(1000)
    # Step 12: Click Textbox "Search"
    page.get_by_role("textbox", name="Search").first.click()
    page.wait_for_timeout(1000)
    # Step 13: Enter "m" in Textbox "Search"
    page.get_by_role("textbox", name="Search").first.fill(tc_data.get("input_4", ""))
    page.wait_for_timeout(1000)
    # Step 14: Click M_Brand1")
    page.get_by_text("M&M_Brand1").click()
    page.wait_for_timeout(1000)
    # Step 15: Click Img "Edit"
    page.get_by_role("img", name="Edit").first.click()
    page.wait_for_timeout(1000)
    # Step 16: Click Text "MAHINDRA AND MAHINDRA LTD."
    page.get_by_text("MAHINDRA AND MAHINDRA LTD.").click()
    page.wait_for_timeout(1000)
    # Step 17: Click Img "Edit"
    page.get_by_role("img", name="Edit").nth(1).click()
    page.wait_for_timeout(1000)
    # Step 18: Click Text "212, Shiv Towers, Tiswadi,"
    page.get_by_text("212, Shiv Towers, Tiswadi,").click()
    page.wait_for_timeout(1000)
    # Step 19: Click child(3) > div")
    page.locator(".align-items-center > div:nth-child(3) > div").click()
    page.wait_for_timeout(1000)
    # Step 20: Click Text "MAHARASHTRA"
    page.get_by_text("MAHARASHTRA").click()
    page.wait_for_timeout(1000)
    # Step 21: Click child(2) > div").first
    page.locator(".jss7 > .d-flex > div > div:nth-child(2) > div").first.click()
    page.wait_for_timeout(1000)
    # Step 22: Click Text "PUNE WH"
    page.get_by_text("PUNE WH").click()
    page.wait_for_timeout(1000)
    # Step 23: Click ")).nth(1)
    page.locator("div").filter(has_text=re.compile(r"^Load Type$")).nth(1).click()
    page.wait_for_timeout(1000)
    # Step 24: Click Text "Full Load"
    page.get_by_text("Full Load").click()
    page.wait_for_timeout(1000)
    # Step 25: Click ")
    page.get_by_text("Return Enabled?").click()
    page.wait_for_timeout(1000)
    # Step 26: Click ")).nth(1)
    page.locator("div").filter(has_text=re.compile(r"^PO Type$")).nth(1).click()
    page.wait_for_timeout(1000)
    # Step 27: Click Text "Inventory Purchase"
    page.get_by_text("Inventory Purchase", exact=True).click()
    page.wait_for_timeout(1000)
    # Step 28: Click ")).nth(1)
    page.locator("div").filter(has_text=re.compile(r"^Type of Inventory Purchase$")).nth(1).click()
    page.wait_for_timeout(1000)
    # Step 29: Click Text "Business Purchase"
    page.get_by_text("Business Purchase", exact=True).click()
    page.wait_for_timeout(1000)
    # Step 30: Click Text "Add New Row"
    page.get_by_text("Add New Row").click()
    page.wait_for_timeout(1000)
    # Step 31: Click Textbox "Search"
    page.get_by_role("textbox", name="Search").nth(1).click()
    page.wait_for_timeout(1000)
    # Step 32: Enter "testing" in Textbox "Search"
    page.get_by_role("textbox", name="Search").nth(1).fill(tc_data.get("input_5", ""))
    page.wait_for_timeout(1000)
    # Step 33: Click Text "Testing Brand (HY) Summer"
    page.get_by_text("Testing Brand (HY) Summer").click()
    page.wait_for_timeout(1000)
    # Step 34: Click "]")
    page.locator("input[name=\"quantity\"]").click()
    page.wait_for_timeout(1000)
    # Step 35: Enter "5" in "]")
    page.locator("input[name=\"quantity\"]").fill(tc_data.get("input_6", ""))
    page.wait_for_timeout(1000)
    # Step 36: Click "]")
    page.locator("input[name=\"unit_price\"]").click()
    page.wait_for_timeout(1000)
    # Step 37: Enter "10" in "]")
    page.locator("input[name=\"unit_price\"]").fill(tc_data.get("input_7", ""))
    page.wait_for_timeout(1000)
    # Step 38: Click Text "Save Changes"
    page.get_by_text("Save Changes").click()
    page.wait_for_timeout(1000)
    # Step 39: Click Text "Save Changes"
    page.get_by_text("Save Changes").click()
    page.wait_for_timeout(1000)
    page.wait_for_timeout(2000)

    checkpoints.mark_passed("Flow executed successfully")

@pytest.mark.tc("TC-ORDERS-002")
def test_TC_ORDERS_002(seller_page: Page, tc_data, base_url, admin_url, checkpoints):
    """Verify Orders page loads with status tabs, filtering by New tab, keyword search, and expanded More filters

    Preconditions: User is logged in to Agrim Seller Dashboard

    Expected Result: Orders page loads with all status tabs visible (All Orders, New, Accepted, Packed, Ready for Dispatch, Picked Up, Dispatched, Rejected, Cancelled). Clicking New tab filters to new orders with Accept/Reject buttons. Search filters orders by keyword. More filter expands to show Warehouses, Payment Status, and Doc Status options.
    """
    page = seller_page
    # Step 1: Navigate to Navigate to https://supplier-dev.agrim.app/
    page.goto(base_url + "")
    try:
        page.wait_for_load_state("networkidle", timeout=5000)
    except Exception:
        pass
    # Step 2: Click Click Orders
    page.get_by_role("link", name="Orders").click()
    page.wait_for_timeout(500)
    # Step 3: Click Click 2
    page.get_by_role("button", name="2").click()
    page.wait_for_timeout(500)
    # Step 4: Click Click Clear All
    page.get_by_role("button", name="Clear All").click()
    page.wait_for_timeout(500)
    # Step 5: Click Click New
    page.get_by_role("button", name="New").click()
    page.wait_for_timeout(500)
    # Verify: New orders tab active and filtered
    expect(page.locator("body")).to_contain_text("New", timeout=10000)
    # Step 6: Enter "PO" in Enter "PO" in search-product-name-sku-brand
    page.get_by_placeholder("Search Product Name, SKU, Brand").fill(tc_data.get("input_1", ""))
    # Verify: Search results filtered by keyword
    expect(page.locator("body")).to_contain_text("PO", timeout=10000)
    # Step 7: Click Click More
    page.get_by_role("button", name="More").click()
    page.wait_for_timeout(500)
    # Verify: More filters expand showing additional options
    expect(page.locator("body")).to_contain_text("Warehouses", timeout=10000)
    # Step 8: Enter "" in Enter "" in search-product-name-sku-brand
    page.get_by_placeholder("Search Product Name, SKU, Brand").fill(tc_data.get("input_2", ""))
    # Step 9: Click Click All Orders
    page.get_by_role("button", name="All Orders").click()
    page.wait_for_timeout(500)

    # ── Final wait before closing ──
    page.wait_for_timeout(2000)
    checkpoints.mark_passed("All 3 verification(s) passed")

@pytest.mark.tc("TC-ORDERS-003")
def test_TC_ORDERS_003(seller_page: Page, tc_data, base_url, admin_url, checkpoints):
    """Full PO Lifecycle - New to Picked Up: Accept a new order, pack it, mark ready, and mark picked up through all seller-actionable stages

    Preconditions: Seller is logged in. At least one New order exists.

    Expected Result: Order progresses through New → Accepted → Packed → Ready for Dispatch → Picked Up stages with correct action buttons visible at each stage.
    """
    page = seller_page
    # Step 1: Navigate to Navigate to https://supplier-dev.agrim.app/orders
    page.goto(base_url + "orders")
    try:
        page.wait_for_load_state("networkidle", timeout=5000)
    except Exception:
        pass
    # Verify: Orders page loaded
    expect(page.locator("body")).to_contain_text("All Orders", timeout=10000)
    # Step 2: Click Click New
    page.get_by_role("button", name="New").click()
    page.wait_for_timeout(500)
    # Verify: New orders tab active with Accept/Reject buttons
    expect(page.locator("body")).to_contain_text("Reject", timeout=10000)
    # Step 3: Click Click Accept
    page.get_by_role("button", name="Accept").click()
    page.wait_for_timeout(500)
    # Verify: Order accepted - Accepted tab with Pack buttons
    expect(page.locator("body")).to_contain_text("Pack", timeout=10000)
    # Step 4: Click Click Pack
    page.get_by_role("button", name="Pack").click()
    page.wait_for_timeout(500)
    # Verify: Order packed - Packed tab with Ready Proof and Ready buttons
    expect(page.locator("body")).to_contain_text("Ready Proof", timeout=10000)
    # Step 5: Click Click Ready
    page.get_by_role("button", name="Ready").click()
    page.wait_for_timeout(500)
    # Verify: Order Ready for Dispatch - Picked Up button available
    expect(page.locator("body")).to_contain_text("Picked Up", timeout=10000)
    # Step 6: Click Click Picked Up
    page.get_by_role("button", name="Picked Up").click()
    page.wait_for_timeout(500)
    # Verify: Order Picked Up - final seller stage with Invoice upload available
    expect(page.locator("body")).to_contain_text("Invoice", timeout=10000)

    # ── Final wait before closing ──
    page.wait_for_timeout(2000)
    checkpoints.mark_passed("All 6 verification(s) passed")