"""Orders flow — Purchase Order E2E tests.

Tests are auto-generated by the ATS recorder.
Record a flow in the app, review steps, add assertions, and save.
"""

import re
import pytest
from playwright.sync_api import expect, Page


@pytest.mark.tc("TC-ORDERS-001")
def test_TC_ORDERS_001(page: Page, tc_data, base_url, admin_url, checkpoints):
    """Create Inv PO
    """
    # Step 1: Navigate to Navigate to https://admin-dev.agrim.app/#/login
    page.goto(admin_url + "#/login")
    # Step 2: Enter "amit.dalal@agrim.app" in Textbox "Username"
    page.get_by_role("textbox", name="Username").fill(tc_data.get("input_1", ""))
    page.wait_for_timeout(1000)
    # Step 3: Click Textbox "Password"
    page.get_by_role("textbox", name="Password").click()
    page.wait_for_timeout(1000)
    # Step 4: Press "CapsLock" on Press "CapsLock" on Textbox "Password"
    page.get_by_role("textbox", name="Password").press("CapsLock")
    page.wait_for_timeout(1000)
    # Step 5: Enter "A" in Textbox "Password"
    page.get_by_role("textbox", name="Password").fill(tc_data.get("input_2", ""))
    page.wait_for_timeout(1000)
    # Step 6: Press "CapsLock" on Press "CapsLock" on Textbox "Password"
    page.get_by_role("textbox", name="Password").press("CapsLock")
    page.wait_for_timeout(1000)
    # Step 7: Enter "Amit@12345" in Textbox "Password"
    page.get_by_role("textbox", name="Password").fill(tc_data.get("input_3", ""))
    page.wait_for_timeout(1000)
    # Step 8: Click Button "Sign in"
    page.get_by_role("button", name="Sign in").click()
    page.wait_for_timeout(1000)
    # Step 9: Click Button "user icon Purchase orders"
    page.get_by_role("button", name="user icon Purchase orders").click()
    page.wait_for_timeout(1000)
    # Step 10: Click Menuitem "All Orders"
    page.get_by_role("menuitem", name="All Orders").click()
    page.wait_for_timeout(1000)
    # Step 11: Click Text "Create"
    page.get_by_text("Create", exact=True).click()
    page.wait_for_timeout(1000)
    # Step 12: Click Textbox "Search"
    page.get_by_role("textbox", name="Search").first.click()
    page.wait_for_timeout(1000)
    # Step 13: Enter "m" in Textbox "Search"
    page.get_by_role("textbox", name="Search").first.fill(tc_data.get("input_4", ""))
    page.wait_for_timeout(1000)
    # Step 14: Click M_Brand1")
    page.get_by_text("M&M_Brand1").click()
    page.wait_for_timeout(1000)
    # Step 15: Click Img "Edit"
    page.get_by_role("img", name="Edit").first.click()
    page.wait_for_timeout(1000)
    # Step 16: Click Text "MAHINDRA AND MAHINDRA LTD."
    page.get_by_text("MAHINDRA AND MAHINDRA LTD.").click()
    page.wait_for_timeout(1000)
    # Step 17: Click Img "Edit"
    page.get_by_role("img", name="Edit").nth(1).click()
    page.wait_for_timeout(1000)
    # Step 18: Click Text "212, Shiv Towers, Tiswadi,"
    page.get_by_text("212, Shiv Towers, Tiswadi,").click()
    page.wait_for_timeout(1000)
    # Step 19: Click child(3) > div")
    page.locator(".align-items-center > div:nth-child(3) > div").click()
    page.wait_for_timeout(1000)
    # Step 20: Click Text "MAHARASHTRA"
    page.get_by_text("MAHARASHTRA").click()
    page.wait_for_timeout(1000)
    # Step 21: Click child(2) > div").first
    page.locator(".jss7 > .d-flex > div > div:nth-child(2) > div").first.click()
    page.wait_for_timeout(1000)
    # Step 22: Click Text "PUNE WH"
    page.get_by_text("PUNE WH").click()
    page.wait_for_timeout(1000)
    # Step 23: Click ")).nth(1)
    page.locator("div").filter(has_text=re.compile(r"^Load Type$")).nth(1).click()
    page.wait_for_timeout(1000)
    # Step 24: Click Text "Full Load"
    page.get_by_text("Full Load").click()
    page.wait_for_timeout(1000)
    # Step 25: Click ")
    page.get_by_text("Return Enabled?").click()
    page.wait_for_timeout(1000)
    # Step 26: Click ")).nth(1)
    page.locator("div").filter(has_text=re.compile(r"^PO Type$")).nth(1).click()
    page.wait_for_timeout(1000)
    # Step 27: Click Text "Inventory Purchase"
    page.get_by_text("Inventory Purchase", exact=True).click()
    page.wait_for_timeout(1000)
    # Step 28: Click ")).nth(1)
    page.locator("div").filter(has_text=re.compile(r"^Type of Inventory Purchase$")).nth(1).click()
    page.wait_for_timeout(1000)
    # Step 29: Click Text "Business Purchase"
    page.get_by_text("Business Purchase", exact=True).click()
    page.wait_for_timeout(1000)
    # Step 30: Click Text "Add New Row"
    page.get_by_text("Add New Row").click()
    page.wait_for_timeout(1000)
    # Step 31: Click Textbox "Search"
    page.get_by_role("textbox", name="Search").nth(1).click()
    page.wait_for_timeout(1000)
    # Step 32: Enter "testing" in Textbox "Search"
    page.get_by_role("textbox", name="Search").nth(1).fill(tc_data.get("input_5", ""))
    page.wait_for_timeout(1000)
    # Step 33: Click Text "Testing Brand (HY) Summer"
    page.get_by_text("Testing Brand (HY) Summer").click()
    page.wait_for_timeout(1000)
    # Step 34: Click "]")
    page.locator("input[name=\"quantity\"]").click()
    page.wait_for_timeout(1000)
    # Step 35: Enter "5" in "]")
    page.locator("input[name=\"quantity\"]").fill(tc_data.get("input_6", ""))
    page.wait_for_timeout(1000)
    # Step 36: Click "]")
    page.locator("input[name=\"unit_price\"]").click()
    page.wait_for_timeout(1000)
    # Step 37: Enter "10" in "]")
    page.locator("input[name=\"unit_price\"]").fill(tc_data.get("input_7", ""))
    page.wait_for_timeout(1000)
    # Step 38: Click Text "Save Changes"
    page.get_by_text("Save Changes").click()
    page.wait_for_timeout(1000)
    # Step 39: Click Text "Save Changes"
    page.get_by_text("Save Changes").click()
    page.wait_for_timeout(1000)
    page.wait_for_timeout(2000)

    checkpoints.mark_passed("Flow executed successfully")

