"""Orders flow — Purchase Order E2E tests.

Tests are auto-generated by the ATS recorder.
Record a flow in the app, review steps, add assertions, and save.
"""

import re
import pytest
from playwright.sync_api import expect, Page

@pytest.mark.tc("TC-ORDERS-001")
def test_TC_ORDERS_001(page: Page, tc_data, base_url, admin_url, checkpoints):
    """Create Inv PO
    """
    # Step 1: Navigate to Navigate to https://admin-dev.agrim.app/#/login
    page.goto(admin_url + "#/login")
    # Step 2: Enter "amit.dalal@agrim.app" in Textbox "Username"
    page.get_by_role("textbox", name="Username").fill(tc_data.get("input_1", ""))
    page.wait_for_timeout(1000)
    # Step 3: Click Textbox "Password"
    page.get_by_role("textbox", name="Password").click()
    page.wait_for_timeout(1000)
    # Step 4: Press "CapsLock" on Press "CapsLock" on Textbox "Password"
    page.get_by_role("textbox", name="Password").press("CapsLock")
    page.wait_for_timeout(1000)
    # Step 5: Enter "A" in Textbox "Password"
    page.get_by_role("textbox", name="Password").fill(tc_data.get("input_2", ""))
    page.wait_for_timeout(1000)
    # Step 6: Press "CapsLock" on Press "CapsLock" on Textbox "Password"
    page.get_by_role("textbox", name="Password").press("CapsLock")
    page.wait_for_timeout(1000)
    # Step 7: Enter "Amit@12345" in Textbox "Password"
    page.get_by_role("textbox", name="Password").fill(tc_data.get("input_3", ""))
    page.wait_for_timeout(1000)
    # Step 8: Click Button "Sign in"
    page.get_by_role("button", name="Sign in").click()
    page.wait_for_timeout(1000)
    # Step 9: Click Button "user icon Purchase orders"
    page.get_by_role("button", name="user icon Purchase orders").click()
    page.wait_for_timeout(1000)
    # Step 10: Click Menuitem "All Orders"
    page.get_by_role("menuitem", name="All Orders").click()
    page.wait_for_timeout(1000)
    # Step 11: Click Text "Create"
    page.get_by_text("Create", exact=True).click()
    page.wait_for_timeout(1000)
    # Step 12: Click Textbox "Search"
    page.get_by_role("textbox", name="Search").first.click()
    page.wait_for_timeout(1000)
    # Step 13: Enter "m" in Textbox "Search"
    page.get_by_role("textbox", name="Search").first.fill(tc_data.get("input_4", ""))
    page.wait_for_timeout(1000)
    # Step 14: Click M_Brand1")
    page.get_by_text("M&M_Brand1").click()
    page.wait_for_timeout(1000)
    # Step 15: Click Img "Edit"
    page.get_by_role("img", name="Edit").first.click()
    page.wait_for_timeout(1000)
    # Step 16: Click Text "MAHINDRA AND MAHINDRA LTD."
    page.get_by_text("MAHINDRA AND MAHINDRA LTD.").click()
    page.wait_for_timeout(1000)
    # Step 17: Click Img "Edit"
    page.get_by_role("img", name="Edit").nth(1).click()
    page.wait_for_timeout(1000)
    # Step 18: Click Text "212, Shiv Towers, Tiswadi,"
    page.get_by_text("212, Shiv Towers, Tiswadi,").click()
    page.wait_for_timeout(1000)
    # Step 19: Click child(3) > div")
    page.locator(".align-items-center > div:nth-child(3) > div").click()
    page.wait_for_timeout(1000)
    # Step 20: Click Text "MAHARASHTRA"
    page.get_by_text("MAHARASHTRA").click()
    page.wait_for_timeout(1000)
    # Step 21: Click child(2) > div").first
    page.locator(".jss7 > .d-flex > div > div:nth-child(2) > div").first.click()
    page.wait_for_timeout(1000)
    # Step 22: Click Text "PUNE WH"
    page.get_by_text("PUNE WH").click()
    page.wait_for_timeout(1000)
    # Step 23: Click ")).nth(1)
    page.locator("div").filter(has_text=re.compile(r"^Load Type$")).nth(1).click()
    page.wait_for_timeout(1000)
    # Step 24: Click Text "Full Load"
    page.get_by_text("Full Load").click()
    page.wait_for_timeout(1000)
    # Step 25: Click ")
    page.get_by_text("Return Enabled?").click()
    page.wait_for_timeout(1000)
    # Step 26: Click ")).nth(1)
    page.locator("div").filter(has_text=re.compile(r"^PO Type$")).nth(1).click()
    page.wait_for_timeout(1000)
    # Step 27: Click Text "Inventory Purchase"
    page.get_by_text("Inventory Purchase", exact=True).click()
    page.wait_for_timeout(1000)
    # Step 28: Click ")).nth(1)
    page.locator("div").filter(has_text=re.compile(r"^Type of Inventory Purchase$")).nth(1).click()
    page.wait_for_timeout(1000)
    # Step 29: Click Text "Business Purchase"
    page.get_by_text("Business Purchase", exact=True).click()
    page.wait_for_timeout(1000)
    # Step 30: Click Text "Add New Row"
    page.get_by_text("Add New Row").click()
    page.wait_for_timeout(1000)
    # Step 31: Click Textbox "Search"
    page.get_by_role("textbox", name="Search").nth(1).click()
    page.wait_for_timeout(1000)
    # Step 32: Enter "testing" in Textbox "Search"
    page.get_by_role("textbox", name="Search").nth(1).fill(tc_data.get("input_5", ""))
    page.wait_for_timeout(1000)
    # Step 33: Click Text "Testing Brand (HY) Summer"
    page.get_by_text("Testing Brand (HY) Summer").click()
    page.wait_for_timeout(1000)
    # Step 34: Click "]")
    page.locator("input[name=\"quantity\"]").click()
    page.wait_for_timeout(1000)
    # Step 35: Enter "5" in "]")
    page.locator("input[name=\"quantity\"]").fill(tc_data.get("input_6", ""))
    page.wait_for_timeout(1000)
    # Step 36: Click "]")
    page.locator("input[name=\"unit_price\"]").click()
    page.wait_for_timeout(1000)
    # Step 37: Enter "10" in "]")
    page.locator("input[name=\"unit_price\"]").fill(tc_data.get("input_7", ""))
    page.wait_for_timeout(1000)
    # Step 38: Click Text "Save Changes"
    page.get_by_text("Save Changes").click()
    page.wait_for_timeout(1000)
    # Step 39: Click Text "Save Changes"
    page.get_by_text("Save Changes").click()
    page.wait_for_timeout(1000)
    page.wait_for_timeout(2000)

    checkpoints.mark_passed("Flow executed successfully")

@pytest.mark.tc("TC-ORDERS-002")
def test_TC_ORDERS_002(seller_page: Page, tc_data, base_url, admin_url, checkpoints):
    """Verify Orders page loads with status tabs, filtering by New tab, keyword search, and expanded More filters

    Preconditions: User is logged in to Agrim Seller Dashboard

    Expected Result: Orders page loads with all status tabs visible (All Orders, New, Accepted, Packed, Ready for Dispatch, Picked Up, Dispatched, Rejected, Cancelled). Clicking New tab filters to new orders with Accept/Reject buttons. Search filters orders by keyword. More filter expands to show Warehouses, Payment Status, and Doc Status options.
    """
    page = seller_page
    # Step 1: Navigate to Navigate to https://supplier-dev.agrim.app/
    page.goto(base_url + "")
    try:
        page.wait_for_load_state("networkidle", timeout=5000)
    except Exception:
        pass
    # Step 2: Click Click Orders
    page.get_by_role("link", name="Orders").click()
    page.wait_for_timeout(500)
    # Step 3: Click Click 2
    page.get_by_role("button", name="2").click()
    page.wait_for_timeout(500)
    # Step 4: Click Click Clear All
    page.get_by_role("button", name="Clear All").click()
    page.wait_for_timeout(500)
    # Step 5: Click Click New
    page.get_by_role("button", name="New").click()
    page.wait_for_timeout(500)
    # Verify: New orders tab active and filtered
    expect(page.locator("body")).to_contain_text("New", timeout=10000)
    # Step 6: Enter "PO" in Enter "PO" in search-product-name-sku-brand
    page.get_by_placeholder("Search Product Name, SKU, Brand").fill(tc_data.get("input_1", ""))
    # Verify: Search results filtered by keyword
    expect(page.locator("body")).to_contain_text("PO", timeout=10000)
    # Step 7: Click Click More
    page.get_by_role("button", name="More").click()
    page.wait_for_timeout(500)
    # Verify: More filters expand showing additional options
    expect(page.locator("body")).to_contain_text("Warehouses", timeout=10000)
    # Step 8: Enter "" in Enter "" in search-product-name-sku-brand
    page.get_by_placeholder("Search Product Name, SKU, Brand").fill(tc_data.get("input_2", ""))
    # Step 9: Click Click All Orders
    page.get_by_role("button", name="All Orders").click()
    page.wait_for_timeout(500)

    # ── Final wait before closing ──
    page.wait_for_timeout(2000)
    checkpoints.mark_passed("All 3 verification(s) passed")

@pytest.mark.tc("TC-ORDERS-003")
def test_TC_ORDERS_003(seller_page: Page, tc_data, base_url, admin_url, checkpoints):
    """Full PO Lifecycle - New to Picked Up: Accept a new order, pack it, mark ready, and mark picked up through all seller-actionable stages

    Preconditions: Seller is logged in. At least one New order exists.

    Expected Result: Order progresses through New → Accepted → Packed → Ready for Dispatch → Picked Up stages with correct action buttons visible at each stage.
    """
    page = seller_page
    # Step 1: Navigate to Navigate to https://supplier-dev.agrim.app/orders
    page.goto(base_url + "orders")
    try:
        page.wait_for_load_state("networkidle", timeout=5000)
    except Exception:
        pass
    # Verify: Orders page loaded
    expect(page.locator("body")).to_contain_text("All Orders", timeout=10000)
    # Step 2: Click Click New
    page.get_by_role("button", name="New").click()
    page.wait_for_timeout(500)
    # Verify: New orders tab active with Accept/Reject buttons
    expect(page.locator("body")).to_contain_text("Reject", timeout=10000)
    # Step 3: Click Click Accept
    page.get_by_role("button", name="Accept").click()
    page.wait_for_timeout(500)
    # Verify: Order accepted - Accepted tab with Pack buttons
    expect(page.locator("body")).to_contain_text("Pack", timeout=10000)
    # Step 4: Click Click Pack
    page.get_by_role("button", name="Pack").click()
    page.wait_for_timeout(500)
    # Verify: Order packed - Packed tab with Ready Proof and Ready buttons
    expect(page.locator("body")).to_contain_text("Ready Proof", timeout=10000)
    # Step 5: Click Click Ready
    page.get_by_role("button", name="Ready").click()
    page.wait_for_timeout(500)
    # Verify: Order Ready for Dispatch - Picked Up button available
    expect(page.locator("body")).to_contain_text("Picked Up", timeout=10000)
    # Step 6: Click Click Picked Up
    page.get_by_role("button", name="Picked Up").click()
    page.wait_for_timeout(500)
    # Verify: Order Picked Up - final seller stage with Invoice upload available
    expect(page.locator("body")).to_contain_text("Invoice", timeout=10000)

    # ── Final wait before closing ──
    page.wait_for_timeout(2000)
    checkpoints.mark_passed("All 6 verification(s) passed")

@pytest.mark.tc("TC-OLC-001")
def test_TC_OLC_001(seller_page: Page, tc_data, base_url, admin_url, checkpoints):
    """Verify Orders page loads correctly with all tabs, search bar, filters, sort dropdown, and order list

    Preconditions: Seller account is logged in

    Expected Result: Orders page at /orders displays All Orders tab, New/Accepted/Packed tabs, Sort dropdown, Order Type filter, and populated order list with PO entries
    """
    page = seller_page
    # Step 1: Navigate to Navigate to https://supplier-dev.agrim.app/orders
    with checkpoints.step("Step 1: Navigate to Navigate to https://supplier-dev.agrim.app/orders"):
        page.goto(base_url + "orders")
        try:
            page.wait_for_load_state("networkidle", timeout=5000)
        except Exception:
            pass
        # Verify: Orders page loads with correct URL
        expect(page).to_have_url(re.compile(".*" + re.escape("/orders") + ".*"), timeout=10000)
        # Verify: All Orders tab visible
        expect(page.locator("body")).to_contain_text("All Orders", timeout=10000)
        # Verify: Order tabs visible (New, Accepted, Packed)
        expect(page.locator("body")).to_contain_text("New", timeout=10000)
        # Verify: Sort dropdown visible
        expect(page.locator("body")).to_contain_text("Sort", timeout=10000)
        # Verify: Order Type filter visible
        expect(page.locator("body")).to_contain_text("Order Type", timeout=10000)
        # Verify: Order list has items (PO visible)
        expect(page.locator("body")).to_contain_text("PO-", timeout=10000)
    # Step 2: Click Click All Orders
    with checkpoints.step("Step 2: Click Click All Orders"):
        page.get_by_role("button", name="All Orders").click()
        page.wait_for_timeout(500)

    # ── Final wait before closing ──
    page.wait_for_timeout(2000)
    checkpoints.mark_passed("Flow completed - all steps passed")

@pytest.mark.tc("TC-OLC-002")
def test_TC_OLC_002(seller_page: Page, tc_data, base_url, admin_url, checkpoints):
    """Verify Orders page tab counts match visible order lists by clicking through All Orders, New, Accepted, Packed, and Dispatched tabs

    Preconditions: Seller is logged in and on Orders page. Date filter is set to Today.

    Expected Result: Each tab loads correctly. All Orders tab shows populated list with PO entries. Status-specific tabs (New, Accepted, Packed, Dispatched) show either matching orders or empty state when count is 0
    """
    page = seller_page
    # Step 1: Navigate to Navigate to https://supplier-dev.agrim.app/orders
    with checkpoints.step("Step 1: Navigate to Navigate to https://supplier-dev.agrim.app/orders"):
        page.goto(base_url + "orders")
        try:
            page.wait_for_load_state("networkidle", timeout=5000)
        except Exception:
            pass
    # Step 2: Click Click All Orders
    with checkpoints.step("Step 2: Click Click All Orders"):
        page.get_by_role("button", name="All Orders").click()
        page.wait_for_timeout(500)
        # Verify: All Orders tab shows count badge
        expect(page.locator("body")).to_contain_text("All Orders", timeout=10000)
        # Verify: Orders list is visible with PO entries
        expect(page.locator("body")).to_contain_text("PO-", timeout=10000)
    # Step 3: Click Click New
    with checkpoints.step("Step 3: Click Click New"):
        page.get_by_role("button", name="New").click()
        page.wait_for_timeout(500)
        # Verify: New tab selected with 0 orders - empty state
        expect(page.locator("body")).to_contain_text("New", timeout=10000)
    # Step 4: Click Click Accepted
    with checkpoints.step("Step 4: Click Click Accepted"):
        page.get_by_role("button", name="Accepted").click()
        page.wait_for_timeout(500)
        # Verify: Accepted tab shows empty state with 0 orders
        expect(page.locator("body")).to_contain_text("Accepted", timeout=10000)
    # Step 5: Click Click Packed
    with checkpoints.step("Step 5: Click Click Packed"):
        page.get_by_role("button", name="Packed").click()
        page.wait_for_timeout(500)
        # Verify: Packed tab selected and navigated
        expect(page.locator("body")).to_contain_text("Packed", timeout=10000)
    # Step 6: Click Click Dispatched
    with checkpoints.step("Step 6: Click Click Dispatched"):
        page.get_by_role("button", name="Dispatched").click()
        page.wait_for_timeout(500)
        # Verify: Dispatched tab selected and navigated
        expect(page.locator("body")).to_contain_text("Dispatched", timeout=10000)

    # ── Final wait before closing ──
    page.wait_for_timeout(2000)
    checkpoints.mark_passed("Flow completed - all steps passed")


@pytest.mark.tc("TC-OLC-003")
def test_TC_OLC_003(seller_page: Page, tc_data, base_url, admin_url, checkpoints):
    """Verify Orders page search and filter: no-results empty state, search clear on tab switch, Order Type filter presence

    Preconditions: Seller is logged in and on Orders page

    Expected Result: Non-matching search shows 'No Order Found', clearing search restores orders, switching tabs clears active search, Order Type filter is accessible
    """
    page = seller_page
    # Step 1: Navigate to Navigate to https://supplier-dev.agrim.app/orders
    with checkpoints.step("Step 1: Navigate to Navigate to https://supplier-dev.agrim.app/orders"):
        page.goto(base_url + "orders")
        try:
            page.wait_for_load_state("networkidle", timeout=5000)
        except Exception:
            pass
    # Step 2: Enter "zzz" in Enter "zzz" in search-product-name-sku-brand
    with checkpoints.step("Step 2: Enter \"zzz\" in Enter \"zzz\" in search-product-name-sku-brand"):
        page.get_by_placeholder("Search Product Name, SKU, Brand").fill(tc_data.get("input_1", ""))
        # Verify: Non-matching search shows No Order Found
        expect(page.locator("body")).to_contain_text("No Order Found", timeout=10000)
    # Step 3: Enter "" in Enter "" in search-product-name-sku-brand
    with checkpoints.step("Step 3: Enter \"\" in Enter \"\" in search-product-name-sku-brand"):
        page.get_by_placeholder("Search Product Name, SKU, Brand").fill(tc_data.get("input_2", ""))
        # Verify: Orders return after clearing search
        expect(page.locator("body")).to_contain_text("PO-", timeout=10000)
    # Step 4: Enter "zzz" in Enter "zzz" in search-product-name-sku-brand
    with checkpoints.step("Step 4: Enter \"zzz\" in Enter \"zzz\" in search-product-name-sku-brand"):
        page.get_by_placeholder("Search Product Name, SKU, Brand").fill(tc_data.get("input_3", ""))
    # Step 5: Click Click New
    with checkpoints.step("Step 5: Click Click New"):
        page.get_by_role("button", name="New").click()
        page.wait_for_timeout(500)
        # Verify: Tab switch to New works - search cleared on tab change
        expect(page.locator("body")).to_contain_text("New", timeout=10000)
    # Step 6: Click Click Order Type
    with checkpoints.step("Step 6: Click Click Order Type"):
        page.get_by_role("button", name="Order Type").click()
        page.wait_for_timeout(500)
        # Verify: Order Type filter is clickable
        expect(page.locator("body")).to_contain_text("Order Type", timeout=10000)

    # ── Final wait before closing ──
    page.wait_for_timeout(2000)
    checkpoints.mark_passed("Flow completed - all steps passed")

@pytest.mark.tc("TC-OLC-004")
def test_TC_OLC_004(seller_page: Page, tc_data, base_url, admin_url, checkpoints):
    """Verify order cards on All Orders view display correct UI elements: PO#, Box count, Grand Total, product details, Raise ticket action

    Preconditions: Seller is logged in and on Orders page with existing orders

    Expected Result: Order cards display PO numbers, Box counts, Grand Total amounts, product details, and Raise ticket actions
    """
    page = seller_page
    # Step 1: Navigate to Navigate to https://supplier-dev.agrim.app/orders
    with checkpoints.step("Step 1: Navigate to Navigate to https://supplier-dev.agrim.app/orders"):
        page.goto(base_url + "orders")
        try:
            page.wait_for_load_state("networkidle", timeout=5000)
        except Exception:
            pass
        # Verify: Orders page loaded with order cards visible
        expect(page.locator("body")).to_contain_text("PO-", timeout=10000)
        # Verify: Order card shows Box count
        expect(page.locator("body")).to_contain_text("Boxes", timeout=10000)
        # Verify: Order card shows Grand Total
        expect(page.locator("body")).to_contain_text("Total", timeout=10000)
        # Verify: Order card shows Raise ticket action
        expect(page.locator("body")).to_contain_text("Raise ticket", timeout=10000)
        # Verify: Order card shows product details
        expect(page.locator("body")).to_contain_text("Testing", timeout=10000)
    # Step 2: Click Click All Orders
    with checkpoints.step("Step 2: Click Click All Orders"):
        page.get_by_role("button", name="All Orders").click()
        page.wait_for_timeout(500)

    # ── Final wait before closing ──
    page.wait_for_timeout(2000)
    checkpoints.mark_passed("Flow completed - all steps passed")

@pytest.mark.tc("TC-OLC-005")
def test_TC_OLC_005(seller_page: Page, tc_data, base_url, admin_url, checkpoints):
    """Verify Accepted order displays Pack CTA and warehouse info on All Orders view

    Preconditions: Seller is logged in with an Accepted order in the list

    Expected Result: Accepted order shows Pack button and warehouse name (e.g. Goa_WH)
    """
    page = seller_page
    # Step 1: Navigate to Navigate to https://supplier-dev.agrim.app/orders
    with checkpoints.step("Step 1: Navigate to Navigate to https://supplier-dev.agrim.app/orders"):
        page.goto(base_url + "orders")
        try:
            page.wait_for_load_state("networkidle", timeout=5000)
        except Exception:
            pass
        # Verify: Orders page loaded
        expect(page).to_have_url(re.compile(".*" + re.escape("/orders") + ".*"), timeout=10000)
        # Verify: Accepted order visible with Pack button
        expect(page.locator("body")).to_contain_text("Pack", timeout=10000)
        # Verify: Accepted order shows warehouse info
        expect(page.locator("body")).to_contain_text("_WH", timeout=10000)
    # Step 2: Click Click All Orders
    with checkpoints.step("Step 2: Click Click All Orders"):
        page.get_by_role("button", name="All Orders").click()
        page.wait_for_timeout(500)

    # ── Final wait before closing ──
    page.wait_for_timeout(2000)
    checkpoints.mark_passed("Flow completed - all steps passed")


@pytest.mark.tc("TC-OLC-006")
def test_TC_OLC_006(seller_page: Page, tc_data, base_url, admin_url, checkpoints):
    """Verify Packed order displays Ready CTA, Ready Proof, Invoice, and Eway Bill document actions

    Preconditions: Seller is logged in with a Packed order in the list

    Expected Result: Packed order card shows Ready button, Ready Proof action, Invoice action, and Eway Bill action
    """
    page = seller_page
    # Step 1: Navigate to Navigate to https://supplier-dev.agrim.app/orders
    with checkpoints.step("Step 1: Navigate to Navigate to https://supplier-dev.agrim.app/orders"):
        page.goto(base_url + "orders")
        try:
            page.wait_for_load_state("networkidle", timeout=5000)
        except Exception:
            pass
        # Verify: Orders page loaded with order cards
        expect(page.locator("body")).to_contain_text("PO-", timeout=10000)
        # Verify: Packed order shows Ready button
        expect(page.locator("body")).to_contain_text("Ready", timeout=10000)
        # Verify: Packed order shows document actions
        expect(page.locator("body")).to_contain_text("Invoice", timeout=10000)
        # Verify: Packed order shows Ready Proof action
        expect(page.locator("body")).to_contain_text("Ready Proof", timeout=10000)
        # Verify: Packed order shows Eway Bill action
        expect(page.locator("body")).to_contain_text("Eway Bill", timeout=10000)
    # Step 2: Click Click All Orders
    with checkpoints.step("Step 2: Click Click All Orders"):
        page.get_by_role("button", name="All Orders").click()
        page.wait_for_timeout(500)

    # ── Final wait before closing ──
    page.wait_for_timeout(2000)
    checkpoints.mark_passed("Flow completed - all steps passed")


@pytest.mark.tc("TC-OLC-007")
def test_TC_OLC_007(seller_page: Page, tc_data, base_url, admin_url, checkpoints):
    """Verify all status tabs load correctly: Ready for Dispatch with Upload PoP, Dispatched, Rejected, Cancelled

    Preconditions: Seller is logged in and on Orders page

    Expected Result: Ready for Dispatch tab shows Upload PoP button. All status tabs (Dispatched, Rejected, Cancelled) load without errors
    """
    page = seller_page
    # Step 1: Navigate to Navigate to https://supplier-dev.agrim.app/orders
    with checkpoints.step("Step 1: Navigate to Navigate to https://supplier-dev.agrim.app/orders"):
        page.goto(base_url + "orders")
        try:
            page.wait_for_load_state("networkidle", timeout=5000)
        except Exception:
            pass
    # Step 2: Click Click Ready for Dispatch
    with checkpoints.step("Step 2: Click Click Ready for Dispatch"):
        page.get_by_role("button", name="Ready for Dispatch").click()
        page.wait_for_timeout(500)
        # Verify: Ready for Dispatch tab loads
        expect(page.locator("body")).to_contain_text("Ready for Dispatch", timeout=10000)
        # Verify: Upload PoP button visible
        expect(page.locator("body")).to_contain_text("Upload PoP", timeout=10000)
    # Step 3: Click Click Dispatched
    with checkpoints.step("Step 3: Click Click Dispatched"):
        page.get_by_role("button", name="Dispatched").click()
        page.wait_for_timeout(500)
        # Verify: Dispatched tab loads successfully
        expect(page.locator("body")).to_contain_text("Dispatched", timeout=10000)
    # Step 4: Click Click Rejected
    with checkpoints.step("Step 4: Click Click Rejected"):
        page.get_by_role("button", name="Rejected").click()
        page.wait_for_timeout(500)
        # Verify: Rejected tab loads successfully
        expect(page.locator("body")).to_contain_text("Rejected", timeout=10000)
    # Step 5: Click Click Cancelled
    with checkpoints.step("Step 5: Click Click Cancelled"):
        page.get_by_role("button", name="Cancelled").click()
        page.wait_for_timeout(500)
        # Verify: Cancelled tab loads successfully
        expect(page.locator("body")).to_contain_text("Cancelled", timeout=10000)

    # ── Final wait before closing ──
    page.wait_for_timeout(2000)
    checkpoints.mark_passed("Flow completed - all steps passed")


@pytest.mark.tc("TC-OLC-008")
def test_TC_OLC_008(seller_page: Page, tc_data, base_url, admin_url, checkpoints):
    """Verify Payments tab loads with bill tabs (All Bills, Unpaid, Paid, Overdue)

    Preconditions: Seller is logged in

    Expected Result: Payments page shows All Bills, Unpaid, Paid, Overdue tabs
    """
    page = seller_page
    # Step 1: Navigate to Navigate to https://supplier-dev.agrim.app/payments
    with checkpoints.step("Step 1: Navigate to Navigate to https://supplier-dev.agrim.app/payments"):
        page.goto(base_url + "payments")
        try:
            page.wait_for_load_state("networkidle", timeout=5000)
        except Exception:
            pass
        # Verify: Payments page loads at correct URL
        expect(page).to_have_url(re.compile(".*" + re.escape("/payments") + ".*"), timeout=10000)
        # Verify: All Bills tab visible
        expect(page.locator("body")).to_contain_text("All Bills", timeout=10000)
        # Verify: Unpaid tab visible
        expect(page.locator("body")).to_contain_text("Unpaid", timeout=10000)
        # Verify: Paid tab visible
        expect(page.locator("body")).to_contain_text("Paid", timeout=10000)
        # Verify: Overdue tab visible
        expect(page.locator("body")).to_contain_text("Overdue", timeout=10000)
    # Step 2: Click Click All Bills
    with checkpoints.step("Step 2: Click Click All Bills"):
        page.get_by_role("button", name="All Bills").click()
        page.wait_for_timeout(500)

    # ── Final wait before closing ──
    page.wait_for_timeout(2000)
    checkpoints.mark_passed("Flow completed - all steps passed")

@pytest.mark.tc("TC-OLC-009")
def test_TC_OLC_009(seller_page: Page, tc_data, base_url, admin_url, checkpoints):
    """Verify Orders page sort dropdown and all filter options are present: Sort, Order Status, Order Type, Auto Accept, Date filter

    Preconditions: Seller is logged in and on Orders page

    Expected Result: Sort Options, Order Status, Order Type, Auto Accept, and Today date filter are all visible and accessible
    """
    page = seller_page
    # Step 1: Navigate to Navigate to https://supplier-dev.agrim.app/orders
    with checkpoints.step("Step 1: Navigate to Navigate to https://supplier-dev.agrim.app/orders"):
        page.goto(base_url + "orders")
        try:
            page.wait_for_load_state("networkidle", timeout=5000)
        except Exception:
            pass
        # Verify: Orders page loaded
        expect(page).to_have_url(re.compile(".*" + re.escape("/orders") + ".*"), timeout=10000)
        # Verify: Sort Options dropdown visible
        expect(page.locator("body")).to_contain_text("Sort", timeout=10000)
        # Verify: Order Status filter visible
        expect(page.locator("body")).to_contain_text("Order Status", timeout=10000)
        # Verify: Order Type filter visible
        expect(page.locator("body")).to_contain_text("Order Type", timeout=10000)
        # Verify: Auto Accept filter visible
        expect(page.locator("body")).to_contain_text("Auto Accept", timeout=10000)
        # Verify: Date filter visible
        expect(page.locator("body")).to_contain_text("Today", timeout=10000)
    # Step 2: Click Click Sort : Options
    with checkpoints.step("Step 2: Click Click Sort : Options"):
        page.get_by_role("button", name="Sort : Options").click()
        page.wait_for_timeout(500)

    # ── Final wait before closing ──
    page.wait_for_timeout(2000)
    checkpoints.mark_passed("Flow completed - all steps passed")


@pytest.mark.tc("TC-OLC-010")
def test_TC_OLC_010(seller_page: Page, tc_data, base_url, admin_url, checkpoints):
    """Verify sidebar navigation works across all main pages: Orders, Payments, Returns, Deductions

    Preconditions: Seller is logged in

    Expected Result: Sidebar links navigate to Payments (/payments), Returns (/returns), Deductions (/deductions), and back to Orders (/orders) correctly
    """
    page = seller_page
    # Step 1: Navigate to Navigate to https://supplier-dev.agrim.app/orders
    with checkpoints.step("Step 1: Navigate to Navigate to https://supplier-dev.agrim.app/orders"):
        page.goto(base_url + "orders")
        try:
            page.wait_for_load_state("networkidle", timeout=5000)
        except Exception:
            pass
    # Step 2: Click Click Payments
    with checkpoints.step("Step 2: Click Click Payments"):
        page.get_by_role("link", name="Payments").click()
        page.wait_for_timeout(500)
        # Verify: Payments page loaded via sidebar
        expect(page).to_have_url(re.compile(".*" + re.escape("/payments") + ".*"), timeout=10000)
    # Step 3: Click Click Returns
    with checkpoints.step("Step 3: Click Click Returns"):
        page.get_by_role("link", name="Returns").click()
        page.wait_for_timeout(500)
        # Verify: Returns page loaded via sidebar
        expect(page).to_have_url(re.compile(".*" + re.escape("/returns") + ".*"), timeout=10000)
        # Verify: Returns page shows Return Initiated tab
        expect(page.locator("body")).to_contain_text("Return Initiated", timeout=10000)
    # Step 4: Click Click Deductions
    with checkpoints.step("Step 4: Click Click Deductions"):
        page.get_by_role("link", name="Deductions").click()
        page.wait_for_timeout(500)
        # Verify: Deductions page loaded via sidebar
        expect(page).to_have_url(re.compile(".*" + re.escape("/deductions") + ".*"), timeout=10000)
        # Verify: Deductions shows All tab
        expect(page.locator("body")).to_contain_text("All", timeout=10000)
    # Step 5: Click Click Orders
    with checkpoints.step("Step 5: Click Click Orders"):
        page.get_by_role("link", name="Orders").click()
        page.wait_for_timeout(500)
        # Verify: Returned to Orders page via sidebar
        expect(page).to_have_url(re.compile(".*" + re.escape("/orders") + ".*"), timeout=10000)

    # ── Final wait before closing ──
    page.wait_for_timeout(2000)
    checkpoints.mark_passed("Flow completed - all steps passed")


@pytest.mark.tc("TC-OLC-011")
def test_TC_OLC_011(seller_page: Page, tc_data, base_url, admin_url, checkpoints):
    """Verify date filter (Today), Sort Options, and Order Type filter are present on Orders page

    Preconditions: Seller is logged in and on Orders page

    Expected Result: Date filter shows Today, Sort Options and Order Type filters are visible
    """
    page = seller_page
    # Step 1: Navigate to Navigate to https://supplier-dev.agrim.app/orders
    with checkpoints.step("Step 1: Navigate to Navigate to https://supplier-dev.agrim.app/orders"):
        page.goto(base_url + "orders")
        try:
            page.wait_for_load_state("networkidle", timeout=5000)
        except Exception:
            pass
        # Verify: Orders page loaded
        expect(page).to_have_url(re.compile(".*" + re.escape("/orders") + ".*"), timeout=10000)
        # Verify: Date filter visible on Orders page
        expect(page.locator("body")).to_contain_text("Today", timeout=10000)
        # Verify: Sort Options visible on Orders page
        expect(page.locator("body")).to_contain_text("Sort", timeout=10000)
        # Verify: Order Type filter visible on Orders page
        expect(page.locator("body")).to_contain_text("Order Type", timeout=10000)
    # Step 2: Click Click All Orders
    with checkpoints.step("Step 2: Click Click All Orders"):
        page.get_by_role("button", name="All Orders").click()
        page.wait_for_timeout(500)

    # ── Final wait before closing ──
    page.wait_for_timeout(2000)
    checkpoints.mark_passed("Flow completed - all steps passed")