"""Sign Up flow E2E tests.

Tests are auto-generated by the ATS recorder.
Record a flow in the app, review steps, add assertions, and save.
"""

import re
import pytest
from playwright.sync_api import expect, Page


@pytest.mark.tc("TC-SIGNUP-001")
def test_TC_SIGNUP_001(page: Page, tc_data, base_url, admin_url, checkpoints):
    """Signup
    """
    # Step 1: Navigate to Navigate to https://supplier-dev.agrim.app/login
    page.goto(base_url + "/login")
    page.wait_for_load_state("networkidle")
    # Step 2: Click Main "main"
    page.get_by_role("main").get_by_text("Sign Up").click()
    page.wait_for_timeout(500)
    # Step 3: Click Textbox "Mobile * Mobile *"
    page.get_by_role("textbox", name="Mobile * Mobile *").click()
    page.wait_for_timeout(500)
    # Step 4: Enter "9315838689" in Textbox "Mobile * Mobile *"
    page.get_by_role("textbox", name="Mobile * Mobile *").fill(tc_data.get("input_1", ""))
    # Step 5: Click Textbox "Email ID * Email ID *"
    page.get_by_role("textbox", name="Email ID * Email ID *").click()
    page.wait_for_timeout(500)
    # Step 6: Enter "Devesh.iiitd@gmail.com" in Textbox "Email ID * Email ID *"
    page.get_by_role("textbox", name="Email ID * Email ID *").fill(tc_data.get("input_2", ""))
    # Step 7: Click Button "Send OTP for Verification"
    page.get_by_role("button", name="Send OTP for Verification").click()
    page.wait_for_timeout(500)
    # Step 8: Click Textbox "*"
    page.get_by_role("textbox", name="*").first.click()
    page.wait_for_timeout(500)
    # Step 9: Enter "1" in Textbox "*"
    page.get_by_role("textbox", name="*").first.fill(tc_data.get("input_3", ""))
    # Step 10: Enter "2" in Textbox "*"
    page.get_by_role("textbox", name="*").nth(1).fill(tc_data.get("input_4", ""))
    # Step 11: Enter "3" in Textbox "*"
    page.get_by_role("textbox", name="*").nth(2).fill(tc_data.get("input_5", ""))
    # Step 12: Enter "4" in Textbox "*"
    page.get_by_role("textbox", name="*").nth(3).fill(tc_data.get("input_6", ""))
    # Step 13: Enter "5" in Textbox "*"
    page.get_by_role("textbox", name="*").nth(4).fill(tc_data.get("input_7", ""))
    # Step 14: Enter "6" in Textbox "*"
    page.get_by_role("textbox", name="*").nth(5).fill(tc_data.get("input_8", ""))
    # Step 15: Click 3.undefined").first
    page.locator(r".w-\[42px\].h-\[48px\].text-neutral-6.text-center.text-base.rounded-lg.border.border-gray-3.outline-none.focus\:border-gray-2.placeholder\:text-neutral-3.undefined").first.scroll_into_view_if_needed()
    page.locator(r".w-\[42px\].h-\[48px\].text-neutral-6.text-center.text-base.rounded-lg.border.border-gray-3.outline-none.focus\:border-gray-2.placeholder\:text-neutral-3.undefined").first.click()
    page.wait_for_timeout(500)
    # Step 16: Enter "1" in 3.undefined").first
    page.locator(r".w-\[42px\].h-\[48px\].text-neutral-6.text-center.text-base.rounded-lg.border.border-gray-3.outline-none.focus\:border-gray-2.placeholder\:text-neutral-3.undefined").first.scroll_into_view_if_needed()
    page.locator(r".w-\[42px\].h-\[48px\].text-neutral-6.text-center.text-base.rounded-lg.border.border-gray-3.outline-none.focus\:border-gray-2.placeholder\:text-neutral-3.undefined").first.fill(tc_data.get("input_9", ""))
    # Step 17: Enter "2" in child(2)")
    page.locator(r"div:nth-child(3) > .relative > div > .flex.flex-col > .flex > input:nth-child(2)").scroll_into_view_if_needed()
    page.locator(r"div:nth-child(3) > .relative > div > .flex.flex-col > .flex > input:nth-child(2)").fill(tc_data.get("input_10", ""))
    # Step 18: Enter "3" in child(3)")
    page.locator(r"div:nth-child(3) > .relative > div > .flex.flex-col > .flex > input:nth-child(3)").scroll_into_view_if_needed()
    page.locator(r"div:nth-child(3) > .relative > div > .flex.flex-col > .flex > input:nth-child(3)").fill(tc_data.get("input_11", ""))
    # Step 19: Enter "4" in child(4)")
    page.locator(r"div:nth-child(3) > .relative > div > .flex.flex-col > .flex > input:nth-child(4)").scroll_into_view_if_needed()
    page.locator(r"div:nth-child(3) > .relative > div > .flex.flex-col > .flex > input:nth-child(4)").fill(tc_data.get("input_12", ""))
    # Step 20: Enter "5" in child(5)")
    page.locator(r"div:nth-child(3) > .relative > div > .flex.flex-col > .flex > input:nth-child(5)").scroll_into_view_if_needed()
    page.locator(r"div:nth-child(3) > .relative > div > .flex.flex-col > .flex > input:nth-child(5)").fill(tc_data.get("input_13", ""))
    # Step 21: Enter "6" in child(6)")
    page.locator(r"div:nth-child(3) > .relative > div > .flex.flex-col > .flex > input:nth-child(6)").scroll_into_view_if_needed()
    page.locator(r"div:nth-child(3) > .relative > div > .flex.flex-col > .flex > input:nth-child(6)").fill(tc_data.get("input_14", ""))
    # Step 22: Click Button "Confirm Otp"
    page.get_by_role("button", name="Confirm Otp").click()
    page.wait_for_timeout(500)
    # Step 23: Click Textbox "Create Password *"
    page.get_by_role("textbox", name="Create Password *").click()
    page.wait_for_timeout(500)
    # Step 25: Enter "T" in Textbox "Create Password *"
    page.get_by_role("textbox", name="Create Password *").fill(tc_data.get("input_15", ""))
    # Step 27: Enter "Temp@123456" in Textbox "Create Password *"
    page.get_by_role("textbox", name="Create Password *").fill(tc_data.get("input_16", ""))
    # Step 28: Click Textbox "Confirm Password *"
    page.get_by_role("textbox", name="Confirm Password *").click()
    page.wait_for_timeout(500)
    # Step 30: Enter "T" in Textbox "Confirm Password *"
    page.get_by_role("textbox", name="Confirm Password *").fill(tc_data.get("input_17", ""))
    # Step 32: Enter "Temp@123456" in Textbox "Confirm Password *"
    page.get_by_role("textbox", name="Confirm Password *").fill(tc_data.get("input_18", ""))
    # Step 33: Click Button "Complete Sign Up"
    page.get_by_role("button", name="Complete Sign Up").click()
    page.wait_for_timeout(500)
    # Step 34: Click Textbox "PAN * PAN *"
    page.get_by_role("textbox", name="PAN * PAN *").click()
    page.wait_for_timeout(500)
    # Step 35: Enter "AABCF7736N" in Textbox "PAN * PAN *"
    page.get_by_role("textbox", name="PAN * PAN *").fill(tc_data.get("input_19", ""))
    # Step 36: Click Button "Verify Btn right icon" — PAN verification
    page.get_by_role("button", name="Verify Btn right icon").first.click()
    page.wait_for_load_state("networkidle")  # Wait for GST API response
    # Select all GSTIN checkboxes (4 found during recording, adapts to any count)
    _checkboxes = page.get_by_role("checkbox")
    for _i in range(_checkboxes.count()):
        _checkboxes.nth(_i).click(force=True)
        page.wait_for_timeout(300)
    # Click the last "Make Head Branch" button (adapts to any GSTIN count)
    _head_btns = page.get_by_role("button", name="Make Head Branch")
    if _head_btns.count() > 0:
        _head_btns.last.click()
        page.wait_for_timeout(500)
    # Step 42: Click Button "Verify Btn right icon" — GST verification
    page.get_by_role("button", name="Verify Btn right icon").nth(1).click()
    page.wait_for_load_state("networkidle")  # Wait for address API response
    # Step 43: Click Main "main"
    page.get_by_role("main").get_by_text("Use address registered on GST").click()
    page.wait_for_timeout(500)
    # Step 44: Click center > .peer").first
    page.locator(r".flex.gap-2.items-center > .peer").first.scroll_into_view_if_needed()
    page.locator(r".flex.gap-2.items-center > .peer").first.click(force=True)
    page.wait_for_timeout(500)
    # Step 45: Click Button "Verify Btn right icon"
    page.get_by_role("button", name="Verify Btn right icon").nth(2).click()
    page.wait_for_timeout(500)
    # Step 46: Click Textbox "Account Number * Account"
    page.get_by_role("textbox", name="Account Number * Account").click()
    page.wait_for_timeout(500)
    # Step 47: Enter "000890289871772" in Textbox "Account Number * Account"
    page.get_by_role("textbox", name="Account Number * Account").fill(tc_data.get("input_20", ""))
    # Step 48: Click Textbox "Confirm Account Number *"
    page.get_by_role("textbox", name="Confirm Account Number *").click()
    page.wait_for_timeout(500)
    # Step 49: Enter "000890289871772" in Textbox "Confirm Account Number *"
    page.get_by_role("textbox", name="Confirm Account Number *").fill(tc_data.get("input_21", ""))
    # Step 50: Click Textbox "IFSC Code * IFSC Code *"
    page.get_by_role("textbox", name="IFSC Code * IFSC Code *").click()
    page.wait_for_timeout(500)
    # Step 51: Enter "000890289871772" in Textbox "IFSC Code * IFSC Code *"
    page.get_by_role("textbox", name="IFSC Code * IFSC Code *").fill(tc_data.get("input_22", ""))
    # Step 52: Double-click Textbox "IFSC Code * IFSC Code *"
    page.get_by_role("textbox", name="IFSC Code * IFSC Code *").dblclick()
    page.wait_for_timeout(500)
    # Step 53: Enter "SCBL0036078" in Textbox "IFSC Code * IFSC Code *"
    page.get_by_role("textbox", name="IFSC Code * IFSC Code *").fill(tc_data.get("input_23", ""))
    # Step 54: Click Button "Verify Btn right icon"
    page.get_by_role("button", name="Verify Btn right icon").nth(3).click()
    page.wait_for_timeout(500)
    # Step 55: Click "))
    page.get_by_role("main").locator(r"div").filter(has_text=re.compile(r"^Manufacturer$")).scroll_into_view_if_needed()
    page.get_by_role("main").locator(r"div").filter(has_text=re.compile(r"^Manufacturer$")).click()
    page.wait_for_timeout(500)
    # Step 56: Click Button "Create my Account Btn right"
    page.get_by_role("button", name="Create my Account Btn right").click()
    page.wait_for_timeout(500)
    # Step 57: Click Button "Setup My Profile Btn right"
    page.get_by_role("button", name="Setup My Profile Btn right").click()
    page.wait_for_timeout(500)
    # Step 58: Click ")).first
    page.locator(r"div").filter(has_text=re.compile(r"^Click to Upload PANMax file size 5MB$")).first.scroll_into_view_if_needed()
    page.locator(r"div").filter(has_text=re.compile(r"^Click to Upload PANMax file size 5MB$")).first.click()
    page.wait_for_timeout(500)
    # Step 59: page.get_by_role("tabpanel", name="Basic Info").set_input_fi
    page.get_by_role("tabpanel", name="Basic Info").set_input_files("ChatGPT Image May 14, 2026, 02_31_36 PM.png")
    # Step 60: Click Text "Max file size 5MB"
    page.get_by_text("Max file size 5MB").first.click()
    page.wait_for_timeout(500)
    # Step 61: page.get_by_role("tabpanel", name="Basic Info").set_input_fi
    page.get_by_role("tabpanel", name="Basic Info").set_input_files("ChatGPT Image May 14, 2026, 02_31_36 PM.png")
    # Step 62: Click Text "Click to Upload Brand Logo"
    page.get_by_text("Click to Upload Brand Logo").click()
    page.wait_for_timeout(500)
    # Step 63: page.get_by_role("tabpanel", name="Basic Info").set_input_fi
    page.get_by_role("tabpanel", name="Basic Info").set_input_files("ChatGPT Image May 14, 2026, 02_31_36 PM.png")
    # Step 64: Click Textbox "Brand Name *"
    page.get_by_role("textbox", name="Brand Name *").click()
    page.wait_for_timeout(500)
    # Step 66: Enter "TEST AUTO" in Textbox "Brand Name *"
    page.get_by_role("textbox", name="Brand Name *").fill(tc_data.get("input_24", ""))
    # Step 67: Click Text "Upload GST Certificate"
    page.get_by_text("Upload GST Certificate").first.click()
    page.wait_for_timeout(500)
    # Step 68: page.get_by_role("tabpanel", name="Basic Info").set_input_fi
    page.get_by_role("tabpanel", name="Basic Info").set_input_files("ChatGPT Image May 14, 2026, 02_31_36 PM.png")
    # Step 69: Double-click name")
    page.locator(r"#poc-name").dblclick()
    page.wait_for_timeout(500)
    # Step 70: Enter "TEST1" in name")
    page.locator(r"#poc-name").scroll_into_view_if_needed()
    page.locator(r"#poc-name").fill(tc_data.get("input_25", ""))
    # Step 71: Click contact")
    page.locator(r"#poc-contact").scroll_into_view_if_needed()
    page.locator(r"#poc-contact").click()
    page.wait_for_timeout(500)
    # Step 72: Enter "6765654378" in contact")
    page.locator(r"#poc-contact").scroll_into_view_if_needed()
    page.locator(r"#poc-contact").fill(tc_data.get("input_26", ""))
    # Step 73: Click 164096")
    page.locator(r"#poc-name-164096").scroll_into_view_if_needed()
    page.locator(r"#poc-name-164096").click()
    page.wait_for_timeout(500)
    # Step 74: Enter "TEST2" in 164096")
    page.locator(r"#poc-name-164096").scroll_into_view_if_needed()
    page.locator(r"#poc-name-164096").fill(tc_data.get("input_27", ""))
    # Step 75: Click 164096")
    page.locator(r"#poc-contact-164096").scroll_into_view_if_needed()
    page.locator(r"#poc-contact-164096").click()
    page.wait_for_timeout(500)
    # Step 76: Enter "2345678987" in 164096")
    page.locator(r"#poc-contact-164096").scroll_into_view_if_needed()
    page.locator(r"#poc-contact-164096").fill(tc_data.get("input_28", ""))
    # Step 77: Click Text "Upload GST Certificate"
    page.get_by_text("Upload GST Certificate").first.click()
    page.wait_for_timeout(500)
    # Step 78: page.get_by_role("tabpanel", name="Basic Info").set_input_fi
    page.get_by_role("tabpanel", name="Basic Info").set_input_files("ChatGPT Image May 14, 2026, 02_31_36 PM.png")
    # Step 79: Click 164097")
    page.locator(r"#poc-name-164097").scroll_into_view_if_needed()
    page.locator(r"#poc-name-164097").click()
    page.wait_for_timeout(500)
    # Step 80: Enter "TEST 3" in 164097")
    page.locator(r"#poc-name-164097").scroll_into_view_if_needed()
    page.locator(r"#poc-name-164097").fill(tc_data.get("input_29", ""))
    # Step 81: Click 164097")
    page.locator(r"#poc-contact-164097").scroll_into_view_if_needed()
    page.locator(r"#poc-contact-164097").click()
    page.wait_for_timeout(500)
    # Step 82: Enter "3456787657" in 164097")
    page.locator(r"#poc-contact-164097").scroll_into_view_if_needed()
    page.locator(r"#poc-contact-164097").fill(tc_data.get("input_30", ""))
    # Step 83: Click ")).first
    page.locator(r"div").filter(has_text=re.compile(r"^Upload GST CertificateMax file size 5MB$")).first.scroll_into_view_if_needed()
    page.locator(r"div").filter(has_text=re.compile(r"^Upload GST CertificateMax file size 5MB$")).first.click()
    page.wait_for_timeout(500)
    # Step 84: page.get_by_role("tabpanel", name="Basic Info").set_input_fi
    page.get_by_role("tabpanel", name="Basic Info").set_input_files("ChatGPT Image May 14, 2026, 02_31_36 PM.png")
    # Step 85: Click Text "Upload GST Certificate"
    page.get_by_text("Upload GST Certificate").click()
    page.wait_for_timeout(500)
    # Step 86: page.get_by_role("tabpanel", name="Basic Info").set_input_fi
    page.get_by_role("tabpanel", name="Basic Info").set_input_files("ChatGPT Image May 14, 2026, 02_31_36 PM.png")
    # Step 87: Click 164098")
    page.locator(r"#poc-name-164098").scroll_into_view_if_needed()
    page.locator(r"#poc-name-164098").click()
    page.wait_for_timeout(500)
    # Step 88: Enter "" in 164098")
    page.locator(r"#poc-name-164098").scroll_into_view_if_needed()
    page.locator(r"#poc-name-164098").fill(tc_data.get("input_31", ""))
    # Step 89: Click Button "Save and Next Btn right icon"
    page.get_by_role("button", name="Save and Next Btn right icon").click()
    page.wait_for_timeout(500)
    # Step 90: Click Textbox "Warehouse Name *"
    page.get_by_role("textbox", name="Warehouse Name *").click()
    page.wait_for_timeout(500)
    # Step 91: Enter "WAR1" in Textbox "Warehouse Name *"
    page.get_by_role("textbox", name="Warehouse Name *").fill(tc_data.get("input_32", ""))
    # Step 92: Click Combobox "combobox"
    page.get_by_role("combobox").click()
    page.wait_for_timeout(500)
    # Step 93: Click _r_22_")
    page.locator(r"#radix-_r_22_").scroll_into_view_if_needed()
    page.locator(r"#radix-_r_22_").click()
    page.wait_for_timeout(500)
    # Step 94: Click Checkbox "checkbox"
    page.get_by_role("checkbox").nth(2).click(force=True)
    page.wait_for_timeout(500)
    # Step 95: Click Button "Mon"
    page.get_by_role("button", name="Mon").click()
    page.wait_for_timeout(500)
    # Step 96: Click Button "Tue"
    page.get_by_role("button", name="Tue").click()
    page.wait_for_timeout(500)
    # Step 97: Click Button "Wed"
    page.get_by_role("button", name="Wed").click()
    page.wait_for_timeout(500)
    # Step 98: Click Button "Thu"
    page.get_by_role("button", name="Thu").click()
    page.wait_for_timeout(500)
    # Step 99: Click Button "Fri"
    page.get_by_role("button", name="Fri").click()
    page.wait_for_timeout(500)
    # Step 100: Click Button "Sat"
    page.get_by_role("button", name="Sat").click()
    page.wait_for_timeout(500)
    # Step 101: Click Button "Btn left icon Add Holiday"
    page.get_by_role("button", name="Btn left icon Add Holiday").click()
    page.wait_for_timeout(500)
    # Step 102: Click Button "Select Date"
    page.get_by_role("button", name="Select Date").click()
    page.wait_for_timeout(500)
    # Step 103: Select "5" in Field "Choose the Month"
    page.get_by_label("Choose the Month").select_option("5")
    page.wait_for_timeout(500)
    # Step 104: Click Button "Wednesday, June 10th,"
    page.get_by_role("button", name="Wednesday, June 10th,").click()
    page.wait_for_timeout(500)
    # Step 105: Click none")
    page.locator(r".flex.touch-none").scroll_into_view_if_needed()
    page.locator(r".flex.touch-none").click()
    page.wait_for_timeout(500)
    # Step 106: Double-click border")
    page.locator(r".bg-border").dblclick()
    page.wait_for_timeout(500)
    # Step 107: Click Button "Save and Next Btn right icon"
    page.get_by_role("button", name="Save and Next Btn right icon").click()
    page.wait_for_timeout(500)
    # Step 108: Click Combobox "combobox"
    page.get_by_role("combobox").filter(has_text="Select State").click()
    page.wait_for_timeout(500)
    # Step 109: Click Option "Assam"
    page.get_by_role("option", name="Assam").click()
    page.wait_for_timeout(500)
    # Step 110: Click Combobox "combobox"
    page.get_by_role("combobox").filter(has_text="Select docType").click()
    page.wait_for_timeout(500)
    # Step 111: Click Text "Pesticides"
    page.get_by_text("Pesticides").click()
    page.wait_for_timeout(500)
    # Step 112: Click Button "Expiry * Expiry *"
    page.get_by_role("button", name="Expiry * Expiry *").click()
    page.wait_for_timeout(500)
    # Step 113: Select "2029" in Field "Choose the Year"
    page.get_by_label("Choose the Year").select_option("2029")
    page.wait_for_timeout(500)
    # Step 114: Click Button "Thursday, May 10th,"
    page.get_by_role("button", name="Thursday, May 10th,").click()
    page.wait_for_timeout(500)
    # Step 115: Click Text "Click to Upload License for"
    page.get_by_text("Click to Upload License for").click()
    page.wait_for_timeout(500)
    # Step 116: page.get_by_role("tabpanel", name="Compliance").set_input_fi
    page.get_by_role("tabpanel", name="Compliance").set_input_files("ChatGPT Image May 14, 2026, 02_31_36 PM.png")
    # Step 117: Click Text "Max file size 5MB"
    page.get_by_text("Max file size 5MB").click()
    page.wait_for_timeout(500)
    # Step 118: page.get_by_role("tabpanel", name="Compliance").set_input_fi
    page.get_by_role("tabpanel", name="Compliance").set_input_files("ChatGPT Image May 14, 2026, 02_31_36 PM.png")
    # Step 119: Click YY")
    page.get_by_role("button", name="calendar DD/MM/YY").click()
    page.wait_for_timeout(500)
    # Step 120: Click Button "Tuesday, May 12th,"
    page.get_by_role("button", name="Tuesday, May 12th,").click()
    page.wait_for_timeout(500)
    # Step 121: Click Button "Save and Next Btn right icon"
    page.get_by_role("button", name="Save and Next Btn right icon").click()
    page.wait_for_timeout(500)
    # Step 122: Click Textbox "Credit Days"
    page.get_by_role("textbox", name="Credit Days").click()
    page.wait_for_timeout(500)
    # Step 124: Enter "5" in Textbox "Credit Days"
    page.get_by_role("textbox", name="Credit Days").fill(tc_data.get("input_33", ""))
    # Step 125: Click Textbox "Credit Limit to Agrim"
    page.get_by_role("textbox", name="Credit Limit to Agrim").click()
    page.wait_for_timeout(500)
    # Step 126: Click Button "Submit Btn right icon"
    page.get_by_role("button", name="Submit Btn right icon").click()
    page.wait_for_timeout(500)
    # Step 127: Click Button "Setup My Profile Btn right"
    page.get_by_role("button", name="Setup My Profile Btn right").click()
    page.wait_for_timeout(500)
    # Step 128: Click Tab "Operations"
    page.get_by_role("tab", name="Operations").click()
    page.wait_for_timeout(500)
    # Step 129: Click Tab "Compliance"
    page.get_by_role("tab", name="Compliance").click()
    page.wait_for_timeout(500)
    # Step 130: Click Text "Basic InfoOperationsComplianceBusiness Terms"
    page.get_by_text("Basic InfoOperationsComplianceBusiness Terms").click()
    page.wait_for_timeout(500)
    # Step 131: Click Tab "Operations"
    page.get_by_role("tab", name="Operations").click()
    page.wait_for_timeout(500)
    # Step 132: Click Tab "Business Terms"
    page.get_by_role("tab", name="Business Terms").click()
    page.wait_for_timeout(500)

    # ── Final wait before closing ──
    page.wait_for_timeout(2000)
    checkpoints.mark_passed("Flow executed successfully")