"""Sign Up flow E2E tests.

Tests are auto-generated by the ATS recorder.
Record a flow in the app, review steps, add assertions, and save.
"""

import re
import os
import pytest
from playwright.sync_api import expect, Page

# Default test image for all file uploads
TEST_UPLOAD_IMAGE = os.path.join(os.path.dirname(__file__), "..", "..", "fixtures", "test_upload.png")


@pytest.mark.tc("TC-SIGNUP-001")
def test_TC_SIGNUP_001(page: Page, tc_data, base_url, admin_url, checkpoints):
    """Signup
    """
    # Step 1: Navigate to Navigate to https://supplier-dev.agrim.app/login
    page.goto(base_url + "/login")
    page.wait_for_load_state("networkidle")
    # Step 2: Click Main "main"
    page.get_by_role("main").get_by_text("Sign Up").click()
    page.wait_for_timeout(500)
    # Step 3: Click Textbox "Mobile * Mobile *"
    page.get_by_role("textbox", name="Mobile * Mobile *").click()
    page.wait_for_timeout(500)
    # Step 4: Enter "9315838689" in Textbox "Mobile * Mobile *"
    page.get_by_role("textbox", name="Mobile * Mobile *").fill(tc_data.get("input_1", ""))
    # Step 5: Click Textbox "Email ID * Email ID *"
    page.get_by_role("textbox", name="Email ID * Email ID *").click()
    page.wait_for_timeout(500)
    # Step 6: Enter "Devesh.iiitd@gmail.com" in Textbox "Email ID * Email ID *"
    page.get_by_role("textbox", name="Email ID * Email ID *").fill(tc_data.get("input_2", ""))
    # Step 7: Click Button "Send OTP for Verification"
    page.get_by_role("button", name="Send OTP for Verification").click()
    page.wait_for_timeout(500)
    # Step 8: Click Textbox "*"
    page.get_by_role("textbox", name="*").first.click()
    page.wait_for_timeout(500)
    # Step 9: Enter "1" in Textbox "*"
    page.get_by_role("textbox", name="*").first.fill(tc_data.get("input_3", ""))
    # Step 10: Enter "2" in Textbox "*"
    page.get_by_role("textbox", name="*").nth(1).fill(tc_data.get("input_4", ""))
    # Step 11: Enter "3" in Textbox "*"
    page.get_by_role("textbox", name="*").nth(2).fill(tc_data.get("input_5", ""))
    # Step 12: Enter "4" in Textbox "*"
    page.get_by_role("textbox", name="*").nth(3).fill(tc_data.get("input_6", ""))
    # Step 13: Enter "5" in Textbox "*"
    page.get_by_role("textbox", name="*").nth(4).fill(tc_data.get("input_7", ""))
    # Step 14: Enter "6" in Textbox "*"
    page.get_by_role("textbox", name="*").nth(5).fill(tc_data.get("input_8", ""))
    # Step 15: Click 3.undefined").first
    page.locator(r".w-\[42px\].h-\[48px\].text-neutral-6.text-center.text-base.rounded-lg.border.border-gray-3.outline-none.focus\:border-gray-2.placeholder\:text-neutral-3.undefined").first.scroll_into_view_if_needed()
    page.locator(r".w-\[42px\].h-\[48px\].text-neutral-6.text-center.text-base.rounded-lg.border.border-gray-3.outline-none.focus\:border-gray-2.placeholder\:text-neutral-3.undefined").first.click()
    page.wait_for_timeout(500)
    # Step 16: Enter "1" in 3.undefined").first
    page.locator(r".w-\[42px\].h-\[48px\].text-neutral-6.text-center.text-base.rounded-lg.border.border-gray-3.outline-none.focus\:border-gray-2.placeholder\:text-neutral-3.undefined").first.scroll_into_view_if_needed()
    page.locator(r".w-\[42px\].h-\[48px\].text-neutral-6.text-center.text-base.rounded-lg.border.border-gray-3.outline-none.focus\:border-gray-2.placeholder\:text-neutral-3.undefined").first.fill(tc_data.get("input_9", ""))
    # Step 17: Enter "2" in child(2)")
    page.locator(r"div:nth-child(3) > .relative > div > .flex.flex-col > .flex > input:nth-child(2)").scroll_into_view_if_needed()
    page.locator(r"div:nth-child(3) > .relative > div > .flex.flex-col > .flex > input:nth-child(2)").fill(tc_data.get("input_10", ""))
    # Step 18: Enter "3" in child(3)")
    page.locator(r"div:nth-child(3) > .relative > div > .flex.flex-col > .flex > input:nth-child(3)").scroll_into_view_if_needed()
    page.locator(r"div:nth-child(3) > .relative > div > .flex.flex-col > .flex > input:nth-child(3)").fill(tc_data.get("input_11", ""))
    # Step 19: Enter "4" in child(4)")
    page.locator(r"div:nth-child(3) > .relative > div > .flex.flex-col > .flex > input:nth-child(4)").scroll_into_view_if_needed()
    page.locator(r"div:nth-child(3) > .relative > div > .flex.flex-col > .flex > input:nth-child(4)").fill(tc_data.get("input_12", ""))
    # Step 20: Enter "5" in child(5)")
    page.locator(r"div:nth-child(3) > .relative > div > .flex.flex-col > .flex > input:nth-child(5)").scroll_into_view_if_needed()
    page.locator(r"div:nth-child(3) > .relative > div > .flex.flex-col > .flex > input:nth-child(5)").fill(tc_data.get("input_13", ""))
    # Step 21: Enter "6" in child(6)")
    page.locator(r"div:nth-child(3) > .relative > div > .flex.flex-col > .flex > input:nth-child(6)").scroll_into_view_if_needed()
    page.locator(r"div:nth-child(3) > .relative > div > .flex.flex-col > .flex > input:nth-child(6)").fill(tc_data.get("input_14", ""))
    # Step 22: Click Button "Confirm Otp"
    page.get_by_role("button", name="Confirm Otp").click()
    page.wait_for_timeout(500)
    # Step 23: Click Textbox "Create Password *"
    page.get_by_role("textbox", name="Create Password *").click()
    page.wait_for_timeout(500)
    # Step 25: Enter "T" in Textbox "Create Password *"
    page.get_by_role("textbox", name="Create Password *").fill(tc_data.get("input_15", ""))
    # Step 27: Enter "Temp@123456" in Textbox "Create Password *"
    page.get_by_role("textbox", name="Create Password *").fill(tc_data.get("input_16", ""))
    # Step 28: Click Textbox "Confirm Password *"
    page.get_by_role("textbox", name="Confirm Password *").click()
    page.wait_for_timeout(500)
    # Step 30: Enter "T" in Textbox "Confirm Password *"
    page.get_by_role("textbox", name="Confirm Password *").fill(tc_data.get("input_17", ""))
    # Step 32: Enter "Temp@123456" in Textbox "Confirm Password *"
    page.get_by_role("textbox", name="Confirm Password *").fill(tc_data.get("input_18", ""))
    # Step 33: Click Button "Complete Sign Up"
    page.get_by_role("button", name="Complete Sign Up").click()
    page.wait_for_timeout(500)
    # Step 34: Click Textbox "PAN * PAN *"
    page.get_by_role("textbox", name="PAN * PAN *").click()
    page.wait_for_timeout(500)
    # Step 35: Enter "AABCF7736N" in Textbox "PAN * PAN *"
    page.get_by_role("textbox", name="PAN * PAN *").fill(tc_data.get("input_19", ""))
    # Step 36: Click Button "Verify Btn right icon" — PAN verification
    page.get_by_role("button", name="Verify Btn right icon").first.click()
    page.wait_for_load_state("networkidle")  # Wait for GST API response
    # Select all GSTIN checkboxes (4 found during recording, adapts to any count)
    _checkboxes = page.get_by_role("checkbox")
    for _i in range(_checkboxes.count()):
        _checkboxes.nth(_i).click(force=True)
        page.wait_for_timeout(300)
    # Click the last "Make Head Branch" button (adapts to any GSTIN count)
    _head_btns = page.get_by_role("button", name="Make Head Branch")
    if _head_btns.count() > 0:
        _head_btns.last.click()
        page.wait_for_timeout(500)
    # Step 42: Click Button "Verify Btn right icon" — GST verification
    page.get_by_role("button", name="Verify Btn right icon").nth(1).click()
    page.wait_for_load_state("networkidle")  # Wait for address API response
    # Step 43: Click Main "main"
    page.get_by_role("main").get_by_text("Use address registered on GST").click()
    page.wait_for_timeout(500)
    # Step 44: Click center > .peer").first
    page.locator(r".flex.gap-2.items-center > .peer").first.scroll_into_view_if_needed()
    page.locator(r".flex.gap-2.items-center > .peer").first.click(force=True)
    page.wait_for_timeout(500)
    # Step 45: Click Button "Verify Btn right icon"
    page.get_by_role("button", name="Verify Btn right icon").nth(2).click()
    page.wait_for_timeout(500)
    # Step 46: Click Textbox "Account Number * Account"
    page.get_by_role("textbox", name="Account Number * Account").click()
    page.wait_for_timeout(500)
    # Step 47: Enter "000890289871772" in Textbox "Account Number * Account"
    page.get_by_role("textbox", name="Account Number * Account").fill(tc_data.get("input_20", ""))
    # Step 48: Click Textbox "Confirm Account Number *"
    page.get_by_role("textbox", name="Confirm Account Number *").click()
    page.wait_for_timeout(500)
    # Step 49: Enter "000890289871772" in Textbox "Confirm Account Number *"
    page.get_by_role("textbox", name="Confirm Account Number *").fill(tc_data.get("input_21", ""))
    # Step 50: Click Textbox "IFSC Code * IFSC Code *"
    page.get_by_role("textbox", name="IFSC Code * IFSC Code *").click()
    page.wait_for_timeout(500)
    # Step 51: Enter "000890289871772" in Textbox "IFSC Code * IFSC Code *"
    page.get_by_role("textbox", name="IFSC Code * IFSC Code *").fill(tc_data.get("input_22", ""))
    # Step 52: Double-click Textbox "IFSC Code * IFSC Code *"
    page.get_by_role("textbox", name="IFSC Code * IFSC Code *").dblclick()
    page.wait_for_timeout(500)
    # Step 53: Enter "SCBL0036078" in Textbox "IFSC Code * IFSC Code *"
    page.get_by_role("textbox", name="IFSC Code * IFSC Code *").fill(tc_data.get("input_23", ""))
    # Step 54: Click Button "Verify Btn right icon"
    page.get_by_role("button", name="Verify Btn right icon").nth(3).click()
    page.wait_for_timeout(500)
    # Step 55: Click "))
    page.get_by_role("main").locator(r"div").filter(has_text=re.compile(r"^Manufacturer$")).scroll_into_view_if_needed()
    page.get_by_role("main").locator(r"div").filter(has_text=re.compile(r"^Manufacturer$")).click()
    page.wait_for_timeout(500)
    # Step 56: Click Button "Create my Account Btn right"
    page.get_by_role("button", name="Create my Account Btn right").click()
    page.wait_for_timeout(500)
    # Step 57: Click Button "Setup My Profile Btn right"
    page.get_by_role("button", name="Setup My Profile Btn right").click()
    page.wait_for_timeout(500)
    # Step 58: Click ")).first
    page.locator(r"div").filter(has_text=re.compile(r"^Click to Upload PANMax file size 5MB$")).first.scroll_into_view_if_needed()
    with page.expect_file_chooser() as fc_info:
        page.locator(r"div").filter(has_text=re.compile(r"^Click to Upload PANMax file size 5MB$")).first.click()
    fc_info.value.set_files(TEST_UPLOAD_IMAGE)
    page.wait_for_timeout(500)
    # Step 60: Click Text "Max file size 5MB"
    with page.expect_file_chooser() as fc_info:
        page.get_by_text("Max file size 5MB").first.click()
    fc_info.value.set_files(TEST_UPLOAD_IMAGE)
    page.wait_for_timeout(500)
    # Step 62: Click Text "Click to Upload Brand Logo"
    with page.expect_file_chooser() as fc_info:
        page.get_by_text("Click to Upload Brand Logo").click()
    fc_info.value.set_files(TEST_UPLOAD_IMAGE)
    page.wait_for_timeout(500)
    # Step 64: Click Textbox "Brand Name *"
    page.get_by_role("textbox", name="Brand Name *").click()
    page.wait_for_timeout(500)
    # Step 66: Enter "TEST AUTO" in Textbox "Brand Name *"
    page.get_by_role("textbox", name="Brand Name *").fill(tc_data.get("input_24", ""))
    # Step 67: Click Text "Upload GST Certificate"
    with page.expect_file_chooser() as fc_info:
        page.get_by_text("Upload GST Certificate").first.click()
    fc_info.value.set_files(TEST_UPLOAD_IMAGE)
    page.wait_for_timeout(500)
    # Step 69: Double-click name")
    page.locator(r"#poc-name").dblclick()
    page.wait_for_timeout(500)
    # Step 70: Enter "TEST1" in name")
    page.locator(r"#poc-name").scroll_into_view_if_needed()
    page.locator(r"#poc-name").fill(tc_data.get("input_25", ""))
    # Step 71: Click contact")
    page.locator(r"#poc-contact").scroll_into_view_if_needed()
    page.locator(r"#poc-contact").click()
    page.wait_for_timeout(500)
    # Step 72: Enter "6765654378" in contact")
    page.locator(r"#poc-contact").scroll_into_view_if_needed()
    page.locator(r"#poc-contact").fill(tc_data.get("input_26", ""))
    # Step 73: Click 164096")
    page.locator(r"#poc-name-164096").scroll_into_view_if_needed()
    page.locator(r"#poc-name-164096").click()
    page.wait_for_timeout(500)
    # Step 74: Enter "TEST2" in 164096")
    page.locator(r"#poc-name-164096").scroll_into_view_if_needed()
    page.locator(r"#poc-name-164096").fill(tc_data.get("input_27", ""))
    # Step 75: Click 164096")
    page.locator(r"#poc-contact-164096").scroll_into_view_if_needed()
    page.locator(r"#poc-contact-164096").click()
    page.wait_for_timeout(500)
    # Step 76: Enter "2345678987" in 164096")
    page.locator(r"#poc-contact-164096").scroll_into_view_if_needed()
    page.locator(r"#poc-contact-164096").fill(tc_data.get("input_28", ""))
    # Step 77: Click Text "Upload GST Certificate"
    with page.expect_file_chooser() as fc_info:
        page.get_by_text("Upload GST Certificate").first.click()
    fc_info.value.set_files(TEST_UPLOAD_IMAGE)
    page.wait_for_timeout(500)
    # Step 79: Click 164097")
    page.locator(r"#poc-name-164097").scroll_into_view_if_needed()
    page.locator(r"#poc-name-164097").click()
    page.wait_for_timeout(500)
    # Step 80: Enter "TEST 3" in 164097")
    page.locator(r"#poc-name-164097").scroll_into_view_if_needed()
    page.locator(r"#poc-name-164097").fill(tc_data.get("input_29", ""))
    # Step 81: Click 164097")
    page.locator(r"#poc-contact-164097").scroll_into_view_if_needed()
    page.locator(r"#poc-contact-164097").click()
    page.wait_for_timeout(500)
    # Step 82: Enter "3456787657" in 164097")
    page.locator(r"#poc-contact-164097").scroll_into_view_if_needed()
    page.locator(r"#poc-contact-164097").fill(tc_data.get("input_30", ""))
    # Step 83: Click ")).first
    page.locator(r"div").filter(has_text=re.compile(r"^Upload GST CertificateMax file size 5MB$")).first.scroll_into_view_if_needed()
    with page.expect_file_chooser() as fc_info:
        page.locator(r"div").filter(has_text=re.compile(r"^Upload GST CertificateMax file size 5MB$")).first.click()
    fc_info.value.set_files(TEST_UPLOAD_IMAGE)
    page.wait_for_timeout(500)
    # Step 85: Click Text "Upload GST Certificate"
    with page.expect_file_chooser() as fc_info:
        page.get_by_text("Upload GST Certificate").click()
    fc_info.value.set_files(TEST_UPLOAD_IMAGE)
    page.wait_for_timeout(500)
    # Step 87: Click 164098")
    page.locator(r"#poc-name-164098").scroll_into_view_if_needed()
    page.locator(r"#poc-name-164098").click()
    page.wait_for_timeout(500)
    # Step 88: Enter "" in 164098")
    page.locator(r"#poc-name-164098").scroll_into_view_if_needed()
    page.locator(r"#poc-name-164098").fill(tc_data.get("input_31", ""))
    # Step 89: Click Button "Save and Next Btn right icon"
    page.get_by_role("button", name="Save and Next Btn right icon").click()
    page.wait_for_timeout(500)
    # Step 90: Click Textbox "Warehouse Name *"
    page.get_by_role("textbox", name="Warehouse Name *").click()
    page.wait_for_timeout(500)
    # Step 91: Enter "WAR1" in Textbox "Warehouse Name *"
    page.get_by_role("textbox", name="Warehouse Name *").fill(tc_data.get("input_32", ""))
    # Step 92: Click Combobox "combobox"
    page.get_by_role("combobox").click()
    page.wait_for_timeout(500)
    # Step 93: Click _r_22_")
    page.locator(r"#radix-_r_22_").scroll_into_view_if_needed()
    page.locator(r"#radix-_r_22_").click()
    page.wait_for_timeout(500)
    # Step 94: Click Checkbox "checkbox"
    page.get_by_role("checkbox").nth(2).click(force=True)
    page.wait_for_timeout(500)
    # Step 95: Click Button "Mon"
    page.get_by_role("button", name="Mon").click()
    page.wait_for_timeout(500)
    # Step 96: Click Button "Tue"
    page.get_by_role("button", name="Tue").click()
    page.wait_for_timeout(500)
    # Step 97: Click Button "Wed"
    page.get_by_role("button", name="Wed").click()
    page.wait_for_timeout(500)
    # Step 98: Click Button "Thu"
    page.get_by_role("button", name="Thu").click()
    page.wait_for_timeout(500)
    # Step 99: Click Button "Fri"
    page.get_by_role("button", name="Fri").click()
    page.wait_for_timeout(500)
    # Step 100: Click Button "Sat"
    page.get_by_role("button", name="Sat").click()
    page.wait_for_timeout(500)
    # Step 101: Click Button "Btn left icon Add Holiday"
    page.get_by_role("button", name="Btn left icon Add Holiday").click()
    page.wait_for_timeout(500)
    # Step 102: Click Button "Select Date"
    page.get_by_role("button", name="Select Date").click()
    page.wait_for_timeout(500)
    # Step 103: Select "5" in Field "Choose the Month"
    page.get_by_label("Choose the Month").select_option("5")
    page.wait_for_timeout(500)
    # Step 104: Click Button "Wednesday, June 10th,"
    page.get_by_role("button", name="Wednesday, June 10th,").click()
    page.wait_for_timeout(500)
    # Step 105: Click none")
    page.locator(r".flex.touch-none").scroll_into_view_if_needed()
    page.locator(r".flex.touch-none").click()
    page.wait_for_timeout(500)
    # Step 106: Double-click border")
    page.locator(r".bg-border").dblclick()
    page.wait_for_timeout(500)
    # Step 107: Click Button "Save and Next Btn right icon"
    page.get_by_role("button", name="Save and Next Btn right icon").click()
    page.wait_for_timeout(500)
    # Step 108: Click Combobox "combobox"
    page.get_by_role("combobox").filter(has_text="Select State").click()
    page.wait_for_timeout(500)
    # Step 109: Click Option "Assam"
    page.get_by_role("option", name="Assam").click()
    page.wait_for_timeout(500)
    # Step 110: Click Combobox "combobox"
    page.get_by_role("combobox").filter(has_text="Select docType").click()
    page.wait_for_timeout(500)
    # Step 111: Click Text "Pesticides"
    page.get_by_text("Pesticides").click()
    page.wait_for_timeout(500)
    # Step 112: Click Button "Expiry * Expiry *"
    page.get_by_role("button", name="Expiry * Expiry *").click()
    page.wait_for_timeout(500)
    # Step 113: Select "2029" in Field "Choose the Year"
    page.get_by_label("Choose the Year").select_option("2029")
    page.wait_for_timeout(500)
    # Step 114: Click Button "Thursday, May 10th,"
    page.get_by_role("button", name="Thursday, May 10th,").click()
    page.wait_for_timeout(500)
    # Step 115: Click Text "Click to Upload License for"
    with page.expect_file_chooser() as fc_info:
        page.get_by_text("Click to Upload License for").click()
    fc_info.value.set_files(TEST_UPLOAD_IMAGE)
    page.wait_for_timeout(500)
    # Step 117: Click Text "Max file size 5MB"
    with page.expect_file_chooser() as fc_info:
        page.get_by_text("Max file size 5MB").click()
    fc_info.value.set_files(TEST_UPLOAD_IMAGE)
    page.wait_for_timeout(500)
    # Step 119: Click YY")
    page.get_by_role("button", name="calendar DD/MM/YY").click()
    page.wait_for_timeout(500)
    # Step 120: Click Button "Tuesday, May 12th,"
    page.get_by_role("button", name="Tuesday, May 12th,").click()
    page.wait_for_timeout(500)
    # Step 121: Click Button "Save and Next Btn right icon"
    page.get_by_role("button", name="Save and Next Btn right icon").click()
    page.wait_for_timeout(500)
    # Step 122: Click Textbox "Credit Days"
    page.get_by_role("textbox", name="Credit Days").click()
    page.wait_for_timeout(500)
    # Step 124: Enter "5" in Textbox "Credit Days"
    page.get_by_role("textbox", name="Credit Days").fill(tc_data.get("input_33", ""))
    # Step 125: Click Textbox "Credit Limit to Agrim"
    page.get_by_role("textbox", name="Credit Limit to Agrim").click()
    page.wait_for_timeout(500)
    # Step 126: Click Button "Submit Btn right icon"
    page.get_by_role("button", name="Submit Btn right icon").click()
    page.wait_for_timeout(500)
    # Step 127: Click Button "Setup My Profile Btn right"
    page.get_by_role("button", name="Setup My Profile Btn right").click()
    page.wait_for_timeout(500)
    # Step 128: Click Tab "Operations"
    page.get_by_role("tab", name="Operations").click()
    page.wait_for_timeout(500)
    # Step 129: Click Tab "Compliance"
    page.get_by_role("tab", name="Compliance").click()
    page.wait_for_timeout(500)
    # Step 130: Click Text "Basic InfoOperationsComplianceBusiness Terms"
    page.get_by_text("Basic InfoOperationsComplianceBusiness Terms").click()
    page.wait_for_timeout(500)
    # Step 131: Click Tab "Operations"
    page.get_by_role("tab", name="Operations").click()
    page.wait_for_timeout(500)
    # Step 132: Click Tab "Business Terms"
    page.get_by_role("tab", name="Business Terms").click()
    page.wait_for_timeout(500)

    # ── Final wait before closing ──
    page.wait_for_timeout(2000)
    checkpoints.mark_passed("Flow executed successfully")


# ============================================================
# TC-SIGNUP-002..005 — Profile Setup tab verification
# Authored from analyzer data (results/_coverage/TC-SIGNUP-001_latest.json).
# Tests use the seller_page fixture (existing logged-in seller) so they don't
# depend on TC-SIGNUP-001 completing — same UI tabs serve both first-time
# setup and ongoing profile editing.
# ============================================================

def _open_profile(page, seller_url):
    """Navigate to /profile and wait for the tab strip to mount."""
    base = seller_url if seller_url.endswith("/") else seller_url + "/"
    page.goto(base + "profile", wait_until="domcontentloaded")
    try:
        page.wait_for_load_state("networkidle", timeout=10000)
    except Exception:
        pass
    page.locator('[role="tab"], button:has-text("Basic Info")').first.wait_for(
        state="visible", timeout=15000
    )
    page.wait_for_timeout(800)


def _click_profile_tab(page, tab_name):
    """Click a profile setup tab by its visible name; fall back to button:has-text."""
    tab = page.get_by_role("tab", name=tab_name)
    if tab.count() == 0:
        tab = page.locator(f'button:has-text("{tab_name}")').first
    tab.click(force=True)
    page.wait_for_timeout(1000)


@pytest.mark.tc("TC-SIGNUP-002")
def test_TC_SIGNUP_002_basic_info(seller_page: Page, seller_url, tc_data, checkpoints):
    """Profile Setup — Basic Info tab renders expected fields."""
    page = seller_page

    def cp_navigate():
        _open_profile(page, seller_url)

    def cp_open_tab():
        _click_profile_tab(page, "Basic Info")

    def cp_tab_active():
        assert (
            page.locator('[role="tab"][aria-selected="true"]:has-text("Basic Info")').count() > 0
            or page.locator('button:has-text("Basic Info")').count() > 0
        ), "Basic Info tab not visible after click"

    def cp_business_name_field():
        assert (
            page.locator('input[placeholder*="Brand Name" i]').count() > 0
            or page.locator('input[placeholder*="Business" i]').count() > 0
            or page.locator('input[placeholder*="Display Name" i]').count() > 0
        ), "No business / brand name input found on Basic Info tab"

    def cp_contact_section():
        assert (
            page.locator('input[id^="poc-name"]').count() > 0
            or page.locator('input[placeholder*="Name of POC" i]').count() > 0
            or page.locator('input[placeholder*="Contact" i]').count() > 0
        ), "No primary contact (POC) input visible on Basic Info tab"

    def cp_save_present():
        assert (
            page.get_by_role("button", name="Save and Next Btn right icon").count() > 0
            or page.locator('button:has-text("Save and Next"), button:has-text("Save")').count() > 0
        ), "Save / Save and Next button not found on Basic Info tab"

    def cp_no_errors():
        errors = page.locator('[role="alert"]:visible, [class*="toast"]:visible:has-text("error")')
        assert errors.count() == 0, f"Error visible: {errors.first.text_content()[:200]}"

    checkpoints.run("Navigate to /profile", cp_navigate)
    checkpoints.run("Click Basic Info tab", cp_open_tab)
    checkpoints.run("Verify Basic Info tab is active", cp_tab_active)
    checkpoints.run("Verify business / brand name input", cp_business_name_field)
    checkpoints.run("Verify primary contact (POC) input", cp_contact_section)
    checkpoints.run("Verify Save / Save and Next button", cp_save_present)
    checkpoints.run("Confirm no error toasts", cp_no_errors)


@pytest.mark.tc("TC-SIGNUP-003")
def test_TC_SIGNUP_003_operations(seller_page: Page, seller_url, tc_data, checkpoints):
    """Profile Setup — Operations tab renders warehouse, working days, holidays."""
    page = seller_page

    def cp_navigate():
        _open_profile(page, seller_url)

    def cp_open_tab():
        _click_profile_tab(page, "Operations")

    def cp_tab_active():
        assert page.locator('button:has-text("Operations")').count() > 0, \
            "Operations tab not visible"

    def cp_warehouse_field():
        assert (
            page.get_by_role("textbox", name="Warehouse Name *").count() > 0
            or page.locator('input[placeholder*="Warehouse" i]').count() > 0
        ), "Warehouse Name input not found"

    def cp_weekday_selector():
        weekdays = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"]
        present = sum(1 for d in weekdays if page.get_by_role("button", name=d).count() > 0)
        assert present >= 5, f"Expected at least 5 weekday buttons, found {present}"

    def cp_holiday_control():
        assert (
            page.get_by_role("button", name="Btn left icon Add Holiday").count() > 0
            or page.locator('button:has-text("Add Holiday"), button:has-text("Holiday")').count() > 0
        ), "Add Holiday control not found"

    def cp_save_present():
        assert (
            page.get_by_role("button", name="Save and Next Btn right icon").count() > 0
            or page.locator('button:has-text("Save")').count() > 0
        ), "Save button not found on Operations tab"

    checkpoints.run("Navigate to /profile", cp_navigate)
    checkpoints.run("Click Operations tab", cp_open_tab)
    checkpoints.run("Verify Operations tab is active", cp_tab_active)
    checkpoints.run("Verify Warehouse Name input", cp_warehouse_field)
    checkpoints.run("Verify weekday selector (Mon..Sat)", cp_weekday_selector)
    checkpoints.run("Verify Add Holiday control", cp_holiday_control)
    checkpoints.run("Verify Save / Save and Next button", cp_save_present)


@pytest.mark.tc("TC-SIGNUP-004")
def test_TC_SIGNUP_004_compliance(seller_page: Page, seller_url, tc_data, checkpoints):
    """Profile Setup — Compliance tab renders license upload UI."""
    page = seller_page

    def cp_navigate():
        _open_profile(page, seller_url)

    def cp_open_tab():
        _click_profile_tab(page, "Compliance")

    def cp_state_selector():
        assert (
            page.get_by_role("combobox").filter(has_text="Select State").count() > 0
            or page.locator('button[role="combobox"]:has-text("State")').count() > 0
            or page.locator('button:has-text("Select State")').count() > 0
        ), "State selector not found on Compliance tab"

    def cp_doctype_selector():
        assert (
            page.get_by_role("combobox").filter(has_text=re.compile("doc|type", re.I)).count() > 0
            or page.locator('button:has-text("Select doc"), button:has-text("Pesticides"), button:has-text("Fertilizer")').count() > 0
        ), "Document type selector not found"

    def cp_expiry_control():
        assert (
            page.get_by_role("button", name="Expiry * Expiry *").count() > 0
            or page.locator('button:has-text("Expiry")').count() > 0
        ), "Expiry date control not found"

    def cp_upload_area():
        assert (
            page.get_by_text("Click to Upload License for").count() > 0
            or page.locator('input[type="file"]').count() > 0
            or page.get_by_text("Max file size 5MB").count() > 0
        ), "License upload area not found"

    checkpoints.run("Navigate to /profile", cp_navigate)
    checkpoints.run("Click Compliance tab", cp_open_tab)
    checkpoints.run("Verify state selector", cp_state_selector)
    checkpoints.run("Verify document type selector", cp_doctype_selector)
    checkpoints.run("Verify Expiry date control", cp_expiry_control)
    checkpoints.run("Verify license upload area", cp_upload_area)


@pytest.mark.tc("TC-SIGNUP-005")
def test_TC_SIGNUP_005_business_terms(seller_page: Page, seller_url, tc_data, checkpoints):
    """Profile Setup — Business Terms tab renders Credit Days, Credit Limit, Submit."""
    page = seller_page

    def cp_navigate():
        _open_profile(page, seller_url)

    def cp_open_tab():
        _click_profile_tab(page, "Business Terms")

    def cp_credit_days_field():
        assert (
            page.get_by_role("textbox", name="Credit Days").count() > 0
            or page.locator('input[placeholder*="Credit Days" i]').count() > 0
        ), "Credit Days input not found"

    def cp_credit_limit_field():
        assert (
            page.get_by_role("textbox", name="Credit Limit to Agrim").count() > 0
            or page.locator('input[placeholder*="Credit Limit" i]').count() > 0
        ), "Credit Limit input not found"

    def cp_submit_present():
        assert (
            page.get_by_role("button", name="Submit Btn right icon").count() > 0
            or page.locator('button:has-text("Submit"), button:has-text("Save")').count() > 0
        ), "Submit / Save button not found"

    checkpoints.run("Navigate to /profile", cp_navigate)
    checkpoints.run("Click Business Terms tab", cp_open_tab)
    checkpoints.run("Verify Credit Days input", cp_credit_days_field)
    checkpoints.run("Verify Credit Limit to Agrim input", cp_credit_limit_field)
    checkpoints.run("Verify Submit / Save button", cp_submit_present)