#!/usr/bin/env bash
# Create a double-clickable QAmate.app launcher for this checkout (macOS, dev use).
# It runs the app from this folder, so code changes are picked up on next launch.
# Usage: bash scripts/create-mac-launcher.sh [destination-dir]   (default: ~/Applications)
set -euo pipefail
REPO="$(cd "$(dirname "$0")/.." && pwd)"
DEST="${1:-$HOME/Applications}"
APP="$DEST/QAmate.app"

mkdir -p "$DEST"
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

cat > "$APP/Contents/MacOS/QAmate" <<EOF
#!/bin/bash
# Generated by scripts/create-mac-launcher.sh
REPO="$REPO"
LOG="\$HOME/Library/Logs/QAmate.log"
ELECTRON="\$REPO/node_modules/electron/dist/Electron.app"
export PATH="/opt/homebrew/bin:/usr/local/bin:\$PATH"
if [ ! -d "\$ELECTRON" ]; then
  osascript -e 'display alert "QAmate can'"'"'t start" message "Electron is not installed. Run npm install in '"\$REPO"' and try again."'
  exit 1
fi
cd "\$REPO" || exit 1
echo "=== QAmate launch \$(date) ===" >> "\$LOG"
exec open -n -a "\$ELECTRON" --stdout "\$LOG" --stderr "\$LOG" --args "\$REPO"
EOF
chmod +x "$APP/Contents/MacOS/QAmate"

cat > "$APP/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>QAmate</string>
  <key>CFBundleDisplayName</key><string>QAmate</string>
  <key>CFBundleIdentifier</key><string>com.qamate.launcher</string>
  <key>CFBundleExecutable</key><string>QAmate</string>
  <key>CFBundleIconFile</key><string>QAmate</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleVersion</key><string>1</string>
  <key>LSUIElement</key><true/>
</dict>
</plist>
EOF

# Icon from the brand PNG (npm run icon generates it).
PNG="$REPO/assets/branding/qamate-mark-1024.png"
if [ -f "$PNG" ]; then
  ICONSET="$(mktemp -d)/QAmate.iconset"
  mkdir -p "$ICONSET"
  for s in 16 32 128 256 512; do
    sips -z $s $s "$PNG" --out "$ICONSET/icon_${s}x${s}.png" >/dev/null
    sips -z $((s*2)) $((s*2)) "$PNG" --out "$ICONSET/icon_${s}x${s}@2x.png" >/dev/null
  done
  iconutil -c icns "$ICONSET" -o "$APP/Contents/Resources/QAmate.icns"
fi

touch "$APP"
echo "Created $APP"
echo "Open it from Finder/Launchpad/Spotlight, or drag it to the Dock. Logs: ~/Library/Logs/QAmate.log"
